
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `accept`,
        `ache`,
        `achieve`,
        `act`,
        `advertise`,
        `advise`,
        `agree`,
        `answer `,
        `appear
        `,
        `apply`,
        `argue`,
        `arrange`,
        `arrest`,
        `arrive`,
        `ask`,
        `assemble`,
        `attend`,
        `attract`,
        `bake`,
        `bathe`,
        ` become`,
        `begin`,
        `behave`,
        `believe`,
        `book`,
        `bore`,
        `bring`,
        `break`,
        `brush`,
        `build`,
        `buy (bought)`,
        `call`,
        `camp`,
        `care`,
        `celebrate `,
        `change`,
        `check `,
        `choose (chose, chosen)`,
        `clean
        `,
        `clear`,
        `close`,
        `come (came, come)
        `,
        ` command`,
        `compete`,
        `combine `,
        `complete`,
        `compose`,
        `confuse`,
        `consult
        `,
        `contain `,
        `continue`,
        `cook`,
        `correct `,
        `cost (cost)
        `,
        `count `,
        `cover `,
        `create
        `,
        `cut (cut)`,
        `decide`,
        `decorate`,
        `delegate`,
        `demonstrate`,
        `depend on`,
        `destroy `,
        `develop
        `,
        `die `,
        `differ`,
        `discover
        `,
        `discuss
        `,
        `doubt `,
        `draw (drew, drawn)
        `,
        `drink (drank, drunk)`,
        `drive (drove, driven)
        `,
        `dust`,
        `eat (ate, eaten)`,
        `educate
        `,
        `employ`,
        `enter `,
        `entertain`,
        `establish`,
        `excite`,
        `expect `,
        `explain `,
        `face `,
        `find (found)`,
        `fire`,
        `fish`,
        `fit`,
        `forget (forgot, forgotten)`,
        `get (got)`,
        `give (gave, given)
        `,
        `go (went, gone)`,
        `govern`,
        `graze `,
        `handle`,
        `hug`,
        `impress`,
        `improve`,
        `increase`,
        `inform`,
        `instruct`,
        `interest`,
        `invent`,
        `invite`,
        `join`,
        `keep (kept)`,
        `know (knew, known)`,
        `last`,
        `lead (led)
        `,
        `learn`,
        `leave (left)`,
        `let`,
        `lighten`,
        `listen to `,
        `live`,
        `look`,
        `make (made) `,
        `manage`,
        `meet (met)`,
        `need`,
        `note`,
        `observe`,
        `obtain`,
        `offer`,
        `open`,
        `organize`,
        `pack`,
        `paint`,
        `park`,
        `pass`,
        `pay (paid) for`,
        `perform`,
        `pity`,
        `pollute`,
        `publish`,
        `put (put)`,
        `qualify`,
        `rain`,
        `read (read)`,
        `receive`,
        `recognize`,
        `recommend`,
        `refuse`,
        `register`,
        `repair`,
        `report`,
        `represent`,
        `require`,
        `respect`,
        `rest`,
        `ring (rang, rung)`,
        `rise (rose, risen)`,
        `say (said)`,
        `scold`,
        `see (saw, seen)
        `,
        `seem`,
        `sell (sold) `,
        `send (sent)`,
        `serve`,
        `sew (sewed, sewn)`,
        `shock`,
        `sign`,
        `sit (sat)`,
        `snow`,
        `speak (spoke, spoken)`,
        `spend (spent) on`,
        `spread (spread)`,
        `stand (stood) `,
        `stay`,
        `stop`,
        `succeed in `,
        `suffer from`,
        `suggest`,
        `suit`,
        `surprise`,
        ` take (took, taken)`,
        `talk`,
        `taste`,
        `teach (taught)
        `,
        `think (thought)`,
        `tire`,
        `to be (was, were, been)`,
        `tour`,
        `track`,
        `translate`,
        `travel`,
        `turn`,
        `type`,
        `understand (understood)`,
        `use`,
        `vary`,
        `wait for`,
        `walk = go on foot`,
        `want`,
        `wash`,
        `watch`,
        `wear (wore, worn)`,
        `win (won)`,
        `work`,
        `write (wrote, written)`,


    ]

    let aze =[ 
      `qəbul etmək`,
      `ağrı; ağrımaq`,
      `nail olmaq`,
      `hərəkət etmək `,
      `reklam etmək `,
      `məsləhət vermək`,
      `razılaşmaq`,
      `cavab; cavab vermək`,
      `görünmək, peyda olmaq`,
      `müraciət etmək, tətbiq etmək`,
      `mübahisə etmək`,
      `təşkil etmək`,
      `həbs etmək`,
      `çatmaq, gəlmək`,
      `soruşmaq, xahiş etmək`,
      `toplaşmaq, yığmaq, yığışmaq`,
      `iştirak etmək`,
      `cəzb etmək`,
      `bişirmək`,
      `yuyunmaq`,
      `olmaq`,
      `başlamaq`,
      `davranmaq, rəftar etmək`,
      `inanmaq`,
      `kitab; sifariş vermək`,
      `can sıxmaq, sıxılmaq`,
      `gətirmək, çatdırmaq`,
      `fasilə; sındırmaq, dağıtmaq`,
      `fırça; fırçalamaq`,
      `tikmək`,
      `almaq`,
      `zəng etmək, çağırmaq
      `,
      `düşərgə; düşərgə salmaq`,
      `diqqət, qayğı; qayğısına qalmaq`,
      `bayram etmək`,
      `xırda pul; dəyişmək`,
      `yoxlamaq`,
      `seçmək`,
      `təmiz; təmizləmək`,
      `təmiz, aydın; aydınlaşdırmaq`,
      `yaxın, səmimi; örtmək, bağlamaq
      `,
      `gəlmək`,
      `əmr; əmr etmək`,
      `yarışmaq
      `,
      `birlik, kombinat; birləşdirmək`,
      `tam, bütöv; tamamlamaq
      `,
      `bəstələmək`,
      `çaşdırmaq, səhv salmaq`,
      `məsləhətləşmək`,
      `ehtiva etmək, daxil etmək`,
      `davam etmək`,
      `bişirmək`,
      `doğru, düzgün; düzəltmək`,
      `qiyməti olmaq`,
      `saymaq, hesablamaq`,
      `örtmək`,
      `yaratmaq`,
      `kəsmək`,
      `qərara gəlmək`,
      `bəzəmək`,
      `təmsil etmək`,
      `nümayiş etdirmək`,
      `asılı olmaq
      `,
      `dağıtmaq, məhv etmək`,
      `inkişaf etmək`,
      `ölmək`,
      `fərqləndirmək`,
      `kəşf etmək`,
      `müzakirə etmək`,
      `şübhə; şübhələnmək`,
      `şəkil çəkmək; heç-heçə oynamaq`,
      `içki; içmək`,
      `sürmək`,
      `toz; tozunu almaq
      `,
      `yemək`,
      `təhsil vermək, tərbiyə etmək`,
      `işə götürmək, işlətmək`,
      `daxil olmaq`,
      `əyləndirmək`,
      `əsasını qoymaq`,
      `həyəcanlandırmaq`,
      `gözləmək, zənn etmək`,
      `izah etmək`,
      `üz; üzləşmək, qarşılaşmaq`,
      `tapmaq`,
      `yanğın; yandırmaq, işdən çıxartmaq`,
      `balıq; balıq tutmaq`,
      `gümrah; yaraşmaq, uyğunlaşdırmaq`,
      `unutmaq`,
      `əldə etmək, almaq`,
      `vermək`,
      `getmək`,
      `idarə etmək`,
      `otlamaq, otarmaq`,
      `dəstək; öhdəsindən gəlmək`,
      `sarılmaq, qucaqlamaq
      `,
      `təsir etmək, təəssürat yaratmaq`,
      `inkişaf etmək, inkişaf etdirmək`,
      `artmaq, artırmaq`,
      `məlumatlandırmaq
      `,
      `öyrətmək, təlimat vermək`,
      `maraqlandırmaq`,
      `ixtira etmək`,
      `dəvət etmək`,
      `qoşulmaq`,
      `saxlamaq`,
      `bilmək`,
      `sonuncu; davam etmək`,
      `rəhbərlik etmək, arxasınca aparmaq
      `,
      `öyrənmək`,
      `tərk etmək`,
      `icazə vermək`,
      `işıqlandırmaq, aydınlatmaq`,
      `qulaq asmaq, dinləmək`,
      `yaşamaq`,
      `görünmək`,
      `etmək, düzəltmək`,
      `idarə etmək`,
      `görüşmək`,
      `ehtiyac; ehtiyacı olmaq`,
      `qeyd; qeyd etmək`,
      `müşahidə etmək`,
      `almaq, əldə etmək`,
      `təklif; təklif etmək`,
      `açıq; açmaq`,
      `təşkil etmək`,
      `qablaşdırmaq`,
      `boya, rəng; boyamaq`,
      `park; maşın saxlamaq`,
      `keçmək, pas ötürmək`,
      `ödəmək, maaş vermək`,
      `ifa etmək, rol oynamaq
      `,
      `təəssüf; təəssüflənmək`,
      `çirkləndirmək`,
      `nəşr etmək`,
      `qoymaq`,
      `ixtisaslaşdırmaq, məhdudlaşdırmaq
      `,
      `yağış; yağış yağmaq
      `,
      `oxumaq`,
      `qəbul etmək`,
      `tanımaq, ayırd etmək`,
      `tövsiyyə etmək, məsləhət görmək`,
      `imtina etmək`,
      `qeydiyyatdan keçmək`,
      `təmir etmək`,
      `hesabat; hesabat vermək`,
      `təmsil etmək`,
      `tələb etmək`,
      `hörmət etmək`,
      `istirahət etmək`,
      `üzük; zəng etmək`,
      `qalxmaq, çıxmaq, ayağa durmaq`,
      `demək`,
      `danlamaq`,
      `görmək`,
      `görsənmək`,
      `satmaq`,
      `göndərmək`,
      `xidmət göstərmək`,
      `tikmək (paltar)`,
      `zərbə, şok; sarsıtmaq
      `,
      `imzalamaq`,
      `oturmaq`,
      `qar; qar yağmaq`,
      `danışmaq`,
      `xərcləmək`,
      `yaymaq, döşəmək, sərmək, yayılmaq`,
      `durmaq, ayağa qalxmaq`,
      `qalmaq`,
      `dayanmaq`,
      `nail olmaq, müvəffəq olmaq
      `,
      `əziyyət çəkmək`,
      `təklif etmək`,
      `kostyum; yaraşmaq, uyğun olmaq`,
      `təəccübləndirmək`,
      `götürmək`,
      `danışmaq, söhbət etmək`,
      `zövq, dad; dadı gəlmək, dadına baxmaq`,
      `öyrətmək, dərs keçmək`,
      `fikirləşmək`,
      `yormaq, yorulmaq`,
      `olmaq`,
      `tur; səyahət etmək`,
      `iz; izləmək`,
      `tərcümə etmək`,
      `səyahət etmək`,
      `dönmək, yerində fırlanmaq
      `,
      `növ; çap etmək`,
      `başa düşmək`,
      `istifadə etmək, işlətmək`,
      `fərqlənmək, fərqləndirmək`,
      `gözləmək`,
      `gəzmək, piyada getmək`,
      `istəmək`,
      `yumaq, yuyunmaq
      `,
      `qol saatı; baxmaq, seyr etmək`,
      `geyinmək`,
      `qələbə qazanmaq
      `,
      `iş; işləmək`,
      `yazmaq`,






    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 