
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `accompany`,
        `adopt`,
        `alert`,
        `analyze`,
        `applaud`,
        `appoint`,
        `assist`,
        `associate with`,
        `astonish`,
        `attempt`,
        `avoid`,
        `awake`,
        `balance`,
        `bear (bore, born)`,
        `beat (beat, beaten)
        `,
        `betray`,
        `blame for`,
        `blind`,
        `blow (blew, blown) `,
        `boast`,
        `bound`,
        `burgle`,
        `burn (burnt or burned)`,
        `bury`,
        `button`,
        `calculate`,
        `capture`,
        `cheer`,
        `claim`,
        `comb`,
        `compile`,
        `complain`,
        ` consist of`,
        `convert`,
        `convince`,
        `cross`,
        `cultivate`,
        `cure`,
        `cycle`,
        `deal with`,
        `dedicate`,
        `delay`,
        `deny`,
        `depart`,
        `detect`,
        `determine`,
        `devote`,
        `disappoint`,
        `dislike`,
        `display`,
        `distribute`,
        `divide`,
        `divorce`,
        `double`,
        `drop`,
        `dye`,
        `effect`,
        `elect`,
        `encircle`,
        `encourage`,
        `engage`,
        `enlarge`,
        `envy`,
        `excuse = apologize`,
        `exercise`,
        `exhaust`,
        `exist`,
        `express`,
        `feed (fed) `,
        `fill`,
        `fix`,
        `flash`,
        `flourish`,
        `flow`,
        `fool`,
        `force`,
        `form`,
        `frame`,
        `frighten`,
        `graduate`,
        `guarantee from`,
        `guess`,
        `hang (hung)`,
        `heal`,
        `hoist = pick up/raise/lift `,
        `hold (held) `,
        `hop`,
        `identify`,
        `include`,
        `influence`,
        `inhabit`,
        `inquire`,
        `insist on `,
        `inspect`,
        `inspire`,
        `interrogate`,
        `interrupt`,
        `investigate`,
        `involve`,
        `kick`,
        `liberate`,
        `line`,
        `locate`,
        `marry`,
        `melt`,
        `memorize`,
        `mind`,
        `misunderstand`,
        `monitor`,
        `murder`,
        `object to`,
        `occupy`,
        `overcome`,
        `permit`,
        `point`,
        `pray`,
        `prepare`,
        `present`,
        `preserve`,
        `press`,
        `prevent`,
        `print`,
        `prohibit`,
        `promote`,
        `pronounce`,
        `prosper`,
        `provide`,
        `pull`,
        `push`,
        `reach`,
        `record`,
        `recover`,
        `reduce`,
        ` refer to`,
        `reflect`,
        `refresh`,
        `regulate`,
        `relax`,
        `release`,
        `relieve`,
        `rely on`,
        `remain`,
        `remove`,
        `replace`,
        `reply`,
        `reproduce`,
        `request`,
        `resemble`,
        `respond`,
        `retire`,
        `revise`,
        `ride (rode, ridden)
        `,
        `roast`,
        `rob`,
        `rock`,
        `rub`,
        `sail`,
        `satisfy`,
        `save`,
        `score`,
        `search`,
        `separate`,
        `service`,
        `set (set)
        `,
        `settle`,
        `share`,
        `shine (shone)`,
        `shoot (shot)`,
        `shout`,
        `shut (shut) `,
        `signal`,
        `skate`,
        `ski`,
        `smell (smelt)`,
        `smile at`,
        `smoke`,
        `sorry`,
        `sound`,
        `spell`,
        ` spoil (spoilt)`,
        `start`,
        `steam`,
        `store`,
        `strike (struck) `,
        `struck`,
        `struggle`,
        `supply`,
        `suppose`,
        `survive`,
        `suspect`,
        `throw (threw, thrown)`,
        `touch`,
        `trade`,
        `treat`,
        `underline`,
        `value`,
        `vote`,
        `wake (woke, woken) up`,
        `warn`,
        `waste`,









    ]

    let aze =[ 
        `müşayiət etmək, ötürmək (kimisə)`,
        `qəbul etmək, övladlığa götürmək`,
        `xəbərdar; xəbərdarlıq etmək`,
        `təhlil etmək`,
        `alqışlamaq`,
        `təyin etmək`,
        `kömək etmək`,
         `qoşulmaq, əməkdaşlıq etmək, birləşmək`,
         `heyrətə salmaq`,
         `cəhd, təşəbbüs; cəhd etmək`,
         `uzaq durmaq, boyun qaçırtmaq`,
         `oyaq, ayıq; oyanmaq, oyandırmaq`,
         `tarazlaşdırmaq`,
         `dözmək`,
         `döymək, döyülmək, qalib gəlmək`,
         `xəyanət etmək`,
         `günahlandırmaq`,
         `kor; kor etmək`,
         `üfləmək, əsmək`,
         `lövğalıq; özünü öymək, lovğalanmaq`,
         `sərhədləmək`,
         `oğurlamaq`,
         `yandırmaq`,
         `dəfn etmək, basdırmaq`,
         `düymə; düymələmək`,
         `hesablamaq
         `,
         `işğal etmək, zəbt etmək, tutmaq`,
         `şənləndirmək, alqışlamaq`,
         `iddia, istək; iddia etmək`,
         `daraq; daramaq, daranmaq
         `,
         `tərtib eləmək`,
         `şikayətlənmək`,
         `ibarət olmaq`,
         `çevirmək`,
         `inandırmaq`,
         `xaç; keçmək`,
         `əkmək, becərmək`,
         `müalicə etmək`,
         `velosiped sürmək`,
         `bəhs etmək, həll etmək`,
         `həsr etmək, ithaf etmək`,
         `təxirə salmaq, ertələmək`,
         `imtina etmək, rədd etmək`,
         `yola düşmək, ayrılmaq`,
         `müəyyənləşdirmək, ortaya çıxarmaq`,
         `müəyyənləşdirmək`,
         `həsr etmək, sadiq olmaq`,
         `məyus etmək`,
         `xoşlamamaq`,
         `göstərmək`,
         `yaymaq, paylamaq`,
         `bölmək`,
         `boşanmaq, ayrılmaq`,
         `ikiyə vurmaq, ikiqat artırmaq`,
         `damcı; yerə düşmək, damcılamaq`,
         `boyamaq, rəngləmək`,
         `təsir göstərmək`,
         `seçmək (prezident, ...)`,
         `mühasirəyə almaq`,
         `cəsarətləndirmək, həvəsləndirmək`,
         `məşğul olmaq, nişanlanmaq`,
         `genişləndirmək`,
         `paxıl; paxıllıq etmək`,
         `üzr istəmək, bağışlamaq
         `,
         `çalışma, məşq; tətbiq etmək, məşq etmək`,
         `taqətdən salmaq
         `,
         `mövcud olmaq`,
         `ifadə etmək`,
         `yedizdirmək`,
         `doldurmaq`,
         `təmir etmək`,
         `işıq tutmaq, aydınlatmaq`,
         `çiçəklənmək, inkişaf etmək`,
         `axın, cərəyan; axmaq, cərəyan etmək`,
         `axmaqlamaq, səfehləmək`,
         `güc; məcbur etmək, güc tətbiq etmək`,
         `forum, blank; formalaşdırmaq, təşkil etmək`,
         `çərçivə; çərçivələmək`,
         `qorxutmaq`,
         `məzun olmaq`,
         `zəmanət, qarantiya; təminat vermək`,
         `təxmin etmək, zənn etmək`,
         `asmaq`,
         `sağaltmaq`,
         `qldırmaq, yuxarı çəkmək`,
         `saxlamaq, keçirmək`,
         `tullanmaq`,
         `müəyyən etmək, tanımaq`,
         `daxil etmək`,
         `təsir etmək`,
         `məskunlaşmaq, yaşamaq`,
         `soruşmaq, xəbər almaq`,
         `təkid etmək, israr etmək`,
         `yoxlamaq`,
         `ruhlandırmaq`,
         `sorğu-sual etmək`,
         `sözünü kəsmək, maneə olmaq`,
         `araşdırmaq, incələmək, soruşdurmaq`,
         `daxil etmək, əhatə etmək`,
         `təpiklə vurmaq`,
         `azad etmək`,
         `xətt; xətt çəkmək, bir xəttlə düzmək`,
         `yerləşmək`,
         `evlənmək`,
         `ərimək, əritmək`,
         `əzbərləmək`,
         `yaddaş, fikir; nəzərdə tutmaq, etiraz etmək
         `,
         `səhv başa düşmək`,
         `müşahidə etmək, nəzarət etmək`,
         `öldürmək, qətlə yetirmək`,
         `etiraz etmək`,
         `işğal etmək, zəbt etmək`,
         `qalib gəlmək; öhdəsindən gəlmək`,
         `icazə vermək`,
         `nöqtə, əsas fikir; işarələmək, göstərmək`,
         `dua etmək`,
         `hazırlamaq, hazırlaşmaq`,
         `təqdim etmək, hədiyyə etmək`,
         `qorumaq`,
         `basmaq, sıxmaq`,
         `qarşısını almaq`,
         `çap etmək`,
         `qadağan etmək`,
         `yüksəltmək (işdə)
         `,
         `tələffüz etmək`,
         `tərəqqi etmək, inkişaf etmək`,
         `təmin etmək`,
         `dartmaq, çəkmək`,
         `itələmək`,
         `çatmaq`,
         `rekord, qeyd; səsyazmaq, qeyd etmək`,
         `sağalmaq, bərpa olunmaq`,
         `azalmaq, azaltmaq`,
         `istinad etmək, aid olmaq`,
         `əks etdirmək`,
         `yeniləmək`,
         `nizamlamaq`,
        `dincəlmək, rahatlamaq
        `,
        `azad etmək, sərbəst buraxmaq`,
        `yüngülləşdirmək, azaltmaq`,
        `güvənmək, etibar etmək`,
        `qalmaq (qalıq olaraq)`,
        `yox etmək, ortadan qaldırmaq`,
        `yerini dəyişdirmək`,
        `cavab vermək`,
        `yenidən istehsal etmək`,
        `xahiş, sorğu; xahiş etmək, tələb etmək`,
        `bənzəmək, oxşamaq`,
        `cavab vermək, məsuliyyət daşımaq`,
        `təqaüdə çıxmaq, istefaya getmək`,
        `təkrar etmək, yoxlamaq`,
        `sürmək`,
        `qızartmaq`,
        `oğurlamaq`,
        `qaya; yelləmək, sallamaq
        `,
        `ovmaq, ovuşturmaq`,
        `yelkənli gəmi; üzmək, yelkənlə üzmək`,
        `qane olmaq, qane etmək`,
        `qorumaq, xilas etmək`,
        `hesab; qol vurmaq`,
        `axtarmaq`,
        `ayırmaq, bölmək`,
        `xidmət; xidmət göstərmək`,
        `batmaq, təyin etmək`,
        `məskunlaşmaq, həll etmək`,
        `paylaşmaq`,
        `parıldamaq`,
        `atəş açmaq, vurmaq`,
        `qışqırmaq`,
        `bağlamaq, örtmək`,
        `işarə vermək`,
        `konki; konki sürmək`,
        `xizək; xizəklə sürüşmək`,
        `iyi gəlmək, iyləmək`,
        `gülümsəmək`,
        `tüstü; siqaret çəkmək, tüstüləmək`,
        `üzgün; təəssüflənmək, üzr istəmək`,
        `səs; səsi gəlmək, səs vermək`,
        `oxumaq, hecalamaq`,
        `korlamaq`,
        `başlamaq`,
        `buxar; buxara vermək`,
        `mağaza; yükləmək, ehtiyat görmək`,
        `tətil; yandırmaq, vurmaq, toqquşdurmaq`,
        `tətil eləmək, işləməmək`,
        `mübarizə (siyasi); mübarizə aparmaq`,
        `təmin etmək, ehtiyacını qarşılamaq`,
        `fərz etmək, düşünmək`,
        `sağ qalmaq`,
        `şübhəli; şübhələnmək`,
        `atmaq, tullamaq`,
        `toxunmaq`,
        `ticarət; ticarətlə məşğul olmaq`,
        `davranmaq, müalicə etmək`,
        `altından xətt çəkmək`,
        `dəyər; dəyər vermək, qiymətləndirmək`,
        `səs; səs vermək`,
        `yuxudan durmaq, oyanmaq
        `,
        `xəbərdarlıq etmək`,
        `vaxtını və ya pulunu boş-boş sərf etmək`,
        
       


    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 