
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `accuse`,
        `add`,
        `admire`,
        `admit`,
        `allow`,
        `amuse`,
        `announce`,
        `annoy`,
        `apologize`,
        `appreciate`,
        `approach`,
        `attack`,
        `award`,
        `battle`,
        `beg`,
        `belong to `,
        `bite (bit, bitten)`,
        `bloom`,
        `boil`,
        `borrow from`,
        `breathe`,
        `breeze`,
        `can`,
        `cancel`,
        `carry`,
        `catch (caught) `,
        `cause`,
        `chat`,
        `climb`,
        `collect`,
        `communicate`,
        `compare`,
        `concentrate`,
        `concern`,
        `congratulate`,
        `connect`,
        `conquer`,
        `consider`,
        `contact`,
        `control`,
        `copy`,
        `criticize`,
        `cry`,
        `damage`,
        `dance`,
        `declare`,
        `decrease`,
        `defeat`,
        `defend`,
        `define`,
        `delete`,
        `delight`,
        `deliver`,
        `demand`,
        `describe`,
        `design`,
        `desire`,
        `disagree`,
        `disappear`,
        `displease`,
        `disturb`,
        `dream`,
        `dress`,
        `dry`,
        `earn`,
        `empty`,
        `end`,
        `enjoy`,
        `exchange`,
        `exhibit`,
        `explode`,
        `explore`,
        `export`,
        `fail`,
        `fall (fell, fallen)`,
        `feel (felt)
        `,
        `fight`,
        `finish`,
        `fly (flew, flown) `,
        `follow`,
        `forbid (forbade, forbidden)
        `,
        `forgive (forgave, forgiven)`,
        `found`,
        `fry`,
        `gain`,
        `gather`,
        `greet`,
        `grow (grew, grown)`,
        `guard`,
        `guide`,
        `hand`,
        `happen`,
        `harm`,
        `hate`,
        `head`,
        `hear (heard) `,
        `heat`,
        `hide (hid, hidden)`,
        `help`,
        `hope`,
        `hunt`,
        `hurry`,
        `hurt (hurt) `,
        `import`,
        `injure`,
        `introduce`,
        `invade`,
        `joke`,
        `joy`,
        `judge`,
        `jump`,
        `kill`,
        `kiss`,
        `knock`,
        `land`,
        `laugh at`,
        `lecture`,
        `lend (lent) to`,
        `lay (laid, laid, laying) `,
        `lie (lay, lain, lying) `,
        `lie (lied, lied, lying)`,
        `lift`,
        `like`,
        `load`,
        `lock`,
        `lose (lost)
        `,
        `love`,
        `mail`,
        `mark`,
        `mask`,
        `match`,
        `mean`,
        `mend`,
        `miss`,
        `mix`,
        `move`,
        `needle`,
        `notice`,
        `obey`,
        `operate`,
        `order`,
        `own`,
        `pause`,
        `phone`,
        `pick`,
        `place`,
        `plan`,
        `plant`,
        `possess`,
        `please`,
        `post`,
        `practice`,
        `praise`,
        `prefer to`,
        `produce`,
        `promise`,
        `propose`,
        `protect`,
        `protest`,
        `punish`,
        `puzzle`,
        `quarrel with`,
        `question`,
        `raise`,
        `realize`,
        `rebuild`,
        `reconstruct`,
        `reject`,
        `remember`,
        `remind`,
        `rent`,
        `repeat`,
        `research`,
        `restore`,
        `return`,
        `rule`,
        `run (ran, run)`,
        `show (showed, shown)
        `,
        `sing (sang, sung)`,
        `sleep (slept)`,
        `solve`,
        `steal (stole, stolen) `,
        `study`,
        `support`,
        `surround`,
        `swim (swam, swum) `,
        `switch on/off`,
        `tear (tore, torn) `,
        `telephone`,
        `tell (told)
        `,
        `thank`,
        `train`,
        `trust`,
        `try`,
        `visit`,
        `weigh`,
        `welcome`,
        `wish`,
        `wonder`,
        `worry`,





    ]

    let aze =[ 
        `təqsirləndirmək, günahlandırmaq
        `,
        `əlavə etmək`,
        `heyran olmaq `,
        `qəbul etmək, etiraf etmək`,
        `icazə vermək`,
        `əyləndirmək, güldürmək`,
        `elan etmək`,
        `zəhlə tökmək, bezdirmək`,
        `üzr istəmək`,
        `bəyənmək, qiymətləndirmək`,
        `çatmaq, yaxınlaşmaq`,
        `hücum; hücum etmək`,
        `mükafat; mükafatlandırmaq
        `,
        `döyüş; döyüşmək`,
        `yalvarmaq, dilənmək`,
        `məxsus olmaq`,
        `dişləmək`,
        `gül-çiçək açmaq`,
        `qaynamaq, qaynatmaq
        `,
        `borc almaq`,
        `nəfəs almaq`,
        `meh; külək əsmək`,
        `dəmir qab; bacarmaq
        `,
        `imtina etmək`,
        `daşımaq`,
        `tutmaq`,
        `səbəb; səbəb olmaq
        `,
        `danışmaq, söhbət etmək`,
        `dırmaşmaq`,
        `toplamaq, yığmaq`,
        `əlaqə saxlamaq`,
        `müqayisə etmək`,
        `fikrini toplamaq`,
        `narahat olmaq`,
        `təbrik etmək`,
        `birləşdirmək, əlaqə qurmaq`,
        `işğal etmək, zəbt etmək`,
        `hesab etmək, zənn etmək`,
        `təmasda olmaq, əlaqədə olmaq`,
        `idarə etmək, nəzarət etmək`,
        `nüsxə; köçürmək`,
        `tənqid etmək, danlamaq`,
        `ağlamaq`,
        `ziyan, təhlükə; ziyan vurmaq`,
        `rəqs; rəqs etmək`,
        `elan etmək, bəyan etmək
        `,
        `azalmaq, azaltmaq
        `,
        `məğlub etmək`,
        `müdafiə etmək`,
        `müəyyənləşdirmək`,
        `silmək`,
        `fərəhlənmək, zövq almaq
        `,
        `paylamaq, çatdırmaq`,
        `tələb; tələb etmək`,
        `təsvir etmək`,
        `lahiyə, tərtib etmək`,
        `arzulamaq`,
        `razılaşmamaq`,
        `yoxa çıxmaq`,
        `narazı olmaq, əsəbləşmək`,
        `narahat etmək, narahat olmaq`,
        `yuxu, xəyal; arzulamaq`,
        `don, paltar; geyinmək, geyindirmək`,
        `quru, quraq; qurumaq, qurutmaq`,
        `qazanmaq`,
        `boş; boşaltmaq`,
        `son; sonlandırmaq`,
        `xoşlamaq, zövq almaq`,
        `dəyişmək, mübadilə etmək`,
        `sərgiləmək, göstərmək`,
        `partlamaq`,
        `araşdırmaq, tətqiq etmək`,
        `ixrac etmək, satmaq`,
        `uğursuzluğa uğramaq`,
        `payız; yıxılmaq, düşmək`,
        `hiss etmək`,
        `mübarizə aparmaq`,
        `qurtarmaq`,
        `milçək; uçmaq`,
        `izləmək, təqib etmək`,
        `qadağan eləmək`,
        `bağışlamaq`,
        `əsasını qoymaq`,
        `qızartmaq`,
        `qazanmaq`,
        `toplamaq, toplaşmaq
        `,
        `salamlamaq`,
        `böyümək, boy atmaq`,
        `gözətçi, nəzarətçi; qorumaq
        `,
        `bələdçi; bələdçilik etmək`,
        `vermək, uzatmaq, yardım etmək`,
        `baş vermək`,
        `ziyan; ziyan vurmaq`,
        `nifrət etmək`,
        `baş; başçılıq etmək, idarə etmək`,
        `eşitmək`,
        `istilik; qızıştırmaq, isitmək`,
        `gizləmək`,
        `kömək etmək`,
        `ümid etmək`,
        `ov; ovlamaq`,
        `tələsmək`,
        `zədələmək`,
        `idxal etmək, almaq`,
        `zədələmək, zədələnmək`,
        `təqdim etmək`,
        `işğal etmək`,
        `zarafat; zarafat etmək`,
        `əylənmək, sevinmək`,
        `hakim; mühakimə etmək, hökm vermək`,
        `tullanmaq`,
        `öldürmək`,
        `öpmək`,
        `vurmaq`,
        `torpaq; yerə enmək`,
        `gülmək`,
        `mühazirə; mühazirə oxumaq
        `,
        `borc vermək`,
        `sərmək`,
        `uzanmaq, yatmaq, yerləşmək`,
        `yalan danışmaq
        `,
        `qaldırmaq`,
        `bəyənmək, xoşlamaq`,
        `yük; yükləmək`,
        `kilit; kilitləmək`,
        `itirmək, uduzmaq
        `,
        `sevmək`,
        `poçt; poçtla göndərmək`,
        `qiymət, işarə; işarələmək`,
        `maska; maskalanmaq`,
        `nəyəsə uyğun olmaq (rəngə, formaya)
        `,
        `xəsis; məna vermək, nəzərdə tutmaq`,
        `təmir etmək`,
        `darıxmaq, buraxmaq, qaçırmaq`,
        `qarışdırmaq`,
        `hərəkət etmək, köçürmək`,
        `iynə; iynələmək`,
        `görmək, hiss etmək`,
        `tabe olmaq`,
        `idarə etmək`,
        `sifariş etmək, əmr etmək`,
        `sahib olmaq`,
        `fasilə; fasilə vermək`,
        `telefon; zəng etmək`,
        `toplamaq, yığmaq, dərmək`,
        `yer; yerləşdirmək`,
        `plan; planlaşdırmaq`,
        `bitki; yetişdirmək, əkmək`,
        `sahib olmaq`,
        `məmnun olmaq, razı qalmaq`,
        `poçtla göndərmək`,
        `təcrübə keçmək, tətbiq etmək`,
        `tərifləmək`,
        `üstün tutmaq
        `,
        `istehsal etmək`,
        `söz vermək`,
        `təklif etmək`,
        `qorumaq`,
        `etiraz etmək`,
        `cəzalandırmaq`,
        `tapmaca; çətinliyə salmaq`,
        `mübahisə etmək`,
        `sual; sual vermək`,
        `qaldırmaq`,
        `fərqinə varmaq, anlamaq, həyata keçirmək`,
        `yenidən tikmək`,
        `yenidən bərpa etmək`,
        `imtina etmək, rədd etmək`,
        `xatırlamaq, yadda saxlamaq`,
        `xatırlatmaq`,
        `kirayə vermək`,
        `təkrar etmək`,
        `araşdırmaq, tədqiq etmək`,
        `bərpa etmək, təmir etmək`,
        `qayıtmaq, geri dönmək`,
        `qanun, qayda; idarə etmək`,
        `qaçmaq`,
        `göstərmək`,
        `mahnı oxumaq`,
        `yatmaq`,
        `həll etmək`,
        `oğurlamaq`,
        `oxumaq, təhsil almaq
        `,
        `dəstəkləmək`,
        `əhatə etmək`,
        `üzmək`,
        `yandırmaq/söndürmək`,
        `cırmaq`,
        `telefon; zəng etmək`,
        `demək, söyləmək`,
        `təşəkkür etmək`,
        `qatar; məşq etmək`,
        `inanmaq`,
        `cəhd etmək, çalışmaq`,
        `səyahət etmək, baş çəkmək`,
        `çəki, ağırlıq; ölçmək (çəkini)`,
        `salamlamaq`,
        `arzulamaq`,
        `maraqlanmaq, bilmək istəmək`,
        `narahat olmaq`,



    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 