
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `advantage`,
        `adventure`,
        `agency`,
        `alley`,
        `ankle`,
        `anniversary`,
        `annual`,
        `anthem`,
        `aria`,
        `art`,
        `artificial`,
        `aunt`,
        `autumn = fall`,
        `aviation`,
        `bad`,
        `bag`,
        `barrel`,
        `beach`,
        `bee`,
        `before`,
        `best`,
        `black`,
        `brain`,
        `bright`,
        `broad`,
        `butter`,
        `by heart`,
        `candy`,
        `carpet`,
        `cat`,
        `cash`,
        `catastrophic`,
        `cheap`,
        `Cheers`,
        `chess`,
        `chief`,
        `choice`,
        `citizen`,
        `civil`,
        `common`,
        `concert`,
        `confident`,
        `contemporary`,
        `contest`,
        `continent`,
        `conversation`,
        `costume`,
        `cotton`,
        `court`,
        `cruel`,
        `customs`,
        `cupboard`,
        `dark`,
        `day off`,
        `defective`,
        `department`,
        `desert`,
        `destination`,
        `difficult`,
        `diligent`,
        `dinner`,
        `directly`,
        `discrimination`,
        `district`,
        `dock`,
        `dragon`,
        `dreary`,
        `early`,
        `Easter`,
        `economy`,
        `electricity`,
        `enemy = foe `,
        `equator`,
        `equipment`,
        `external`,
        `eye`,
        `extra`,
        `facility`,
        `fact`,
        `fair`,
        `fairy`,
        `fast`,
        `father`,
        `female`,
        `fever`,
        `financial`,
        `flavour`,
        `fluent`,
        `fog`,
        `food`,
        `for ages`,
        `former`,
        `fortnight`,
        `full`,
        `funny`,
        `future`,
        `garbage`,
        `generous`,
        `gentle`,
        `geography`,
        `giraffe`,
        `glory`,
        `gloves`,
        `goods`,
        `grant`,
        `grocer`,
        `grown-up`,
        `growth`,
        `guest`,
        `handful`,
        `handmade`,
        `handsome`,
        `hardly`,
        `hardship`,
        `hazardous`,
        `headmaster`,
        `hero`,
        `hole`,
        `holiday`,
        `house`,
        `illegal`,
        `impolite`,
        `impossible`,
        `incident`,
        `inconsistent`,
        `indefinite`,
        `individual`,
        `illustration`,
        `inn`,
        `interview`,
        `invisible`,
        `irregular`,
        `item`,
        `kettle`,
        `key`,
        `kid`,
        `lamb`,
        `language`,
        `law`,
        `leisure`,
        `level`,
        `literature`,
        `litter`,
        `lonely`,
        `long`,
        `lorry`,
        `machine`,
        `mankind`,
        `mental`,
        `messenger`,
        `method`,
        `military`,
        `miserable`,
        `moment`,
        `mouse, mice`,
        `movie`,
        `neighbour`,
        `news`,
        `North-South-West-East`,
        `nothing`,
        `novel`,
        `nurse`,
        `often`,
        `oil`,
        `old-fashioned `,
        `only`,
        `opportunity`,
        `optimistic`,
        `oval`,
        `oven`,
        `page`,
        `paper`,
        `particular`,
        `peach`,
        `pencil`,
        `penfriend = pen pal `,
        `penny`,
        `pensioner`,
        `percent`,
        `perhaps`,
        `permanent`,
        `person`,
        `picture`,
        `pinafore`,
        `plane`,
        `plank`,
        `plate`,
        `plum`,
        `plump`,
        `pocket`,
        `porridge`,
        `porter`,
        `positive`,
        `pouch`,
        `previous`,
        `probably`,
        `profit`,
        `progress`,
        `project`,
        `proper`,
        `proverb`,
        `pudding`,
        `puppy`,
        `purpose`,
        `quick`,
        `raw`,
        `rather`,
        `reason`,
        `refrigerator`,
        `refugee`,
        `relation`,
        `relative`,
        `renaissance`,
        `resident`,
        `resort`,
        `rest of`,
        `rice`,
        `rosy`,
        `sacrifice`,
        `sale`,
        `same`,
        `sample`,
        `scene`,
        `school`,
        `sea`,
        `seat`,
        `sensational`,
        `sensible`,
        `shallow`,
        `sharp`,
        `shelf, shelves`,
        `shop`,
        `short`,
        `shy`,
        `simple`,
        `sister`,
        `slave`,
        `skin`,
        `sky`,
        `snack`,
        `soap`,
        `somebody = someone`,
        `son`,
        `spectacles=glasses`,
        `spectacular`,
        `spoilt`,
        `state`,
        `step-father`,
        `still`,
        `structure`,
        `suburb`,
        `sudden`,
        `sun`,
        `surface`,
        `surfing`,
        `surname`,
        `sweet`,
        `task`,
        `tea pot`,
        `teenager`,
        `tent`,
        `terrible`,
        `textile`,
        `theory`,
        `thick = dense`,
        `third`,
        `throat`,
        `thumb`,
        `tiger`,
        `tight`,
        `today`,
        `tomato`,
        `tomorrow`,
        `too`,
        `towards`,
        `town`,
        `tragic`,
        `tram`,
        `transfer`,
        `tunnel`,
        `unfair`,
        `unit`,
        `unusual`,
        `upper`,
        `vegetable`,
        `volunteer`,
        `vacant`,
        `wallet`,
        `war`,
        `warehouse`,
        `weak,
        `,
        `wedding`,
        `well-built `,
        `wet`,
        `whole`,
        `wild`,
        `wise`,
        `wonderful`,
        `wound`,
        `zoo`,

    ]

    let aze =[ 
        `üstünlük, fayda`,
        `macəra`,
        `agentlik`,
        `xiyaban`,
        `topuq, ayaq sümüyü`,
        `ildönümü`,
        `illik, hər il edilən`,
        `himn`,
        `ariya`,
        `incəsənət`,
        `süni, əldəqayırma`,
        `xala`,
        `payız`,
        `aviasiya`,
        `pis`,
        `çanta`,
        `çəllək`,
        `çimərlik`,
        `arı`,
        `əvvəl`,
        `ən yaxaşı`,
        `qara`,
        `beyin`,
        `parlaq`,
        `enli, geniş`,
        `yağ`,
        `əzbərdən`,
        `şirniyyat`,
        `xalça`,
        `pişik`,
        `nağd pul`,
        `fəlakətli`,
        `ucuz`,
        `Sizin sağlığınıza`,
        `şahmat`,
        `başçı, rəhbər; əsas, başlıca`,
        `seçim`,
        `vətəndaş`,
        `mədəni, təhsilli, ziyalı`,
        `ümumi, ortaq, adi, sadə`,
        `konsert`,
        `əmin, arxayın`,
        `müasir`,
        `müsabiqə, yarış`,
        `qitə, materik`,
        `söhbət`,
        `kostyum`,
        `pambıq`,
        `məhkəmə`,
        `qəddar, kobud
        `,
        `gömrük`,
        `şkaf`,
        `qara, tünd`,
        `istirahət günü
        `,
        `qüsurlu, zay`,
        `şöbə, bölmə`,
        `səhra`,
        `məqsəd, istiqamət, hədəf`,
        `çətin`,
        `çalışqan`,
        `nahar`,
        `bilavasitə, birbaşa`,
        `ayrı-seçkilik`,
        `rayon, bölgə`,
        `gəmilərin təmir olduğu və saxlandığı yer`,
        `əjdaha`,
        `kədərli, maraqsız, cansıxıcı`,
        `erkən, tez `,
        `Pasxa bayramı
        `,
        `iqtisad`,
        `elektrik`,
        `düşmən`,
        `ekvator`,
        `təchizat, avadanlıq
        `,
        `xarici`,
        `göz`,
        `əlavə`,
        `ləvazimat`,
        `sübut, fakt
        `,
        `ədalətli, sarışın`,
        `sehrli`,
        `sürətli, tez `,
        `ata`,
        `qadın`,
        `istilik, hərarət
        `,
        `maliyyə`,
        `dad`,
        `səlis, axıcı`,
        `duman`,
        `ərzaq`,
        `uzun illər`,
        `keçmiş, öncəki, köhnə`,
        `iki həftə`,
        `dolu`,
        `gülməli`,
        `gələcək`,
        `zibil, tullantı`,
        `səxavətli, əliaçıq`,
        `mülayim, sakit, alicənab`,
        `coğrafiya`,
        `zürafə`,
        `şöhrət`,
        `əlcək`,
        `mal-əmtəə`,
        `xüsusi məqsəd üçün ayrılmış pul, qrant`,
        `baqqal`,
        `böyüklər, saçlı-saqqallı`,
        `böyümə`,
        `qonaq`,
        `bir ovuc`,
        `əl işi`,
        `yaraşıqlı`,
        `zorla, güclə`,
        `çətinlik, maneə
        `,
        `təhlükəli`,
        `sinif rəhbəri`,
        `qəhrəman`,
        `deşik`,
        `bayram, tətil
        `,
        `ev; sığındırmaq, saxlamaq`,
        `qeyri-qanuni `,
        `nəzakətsiz`,
        `qeyri-mümkün`,
        `hadisə`,
        `dəyişkən`,
        `qeyri-müəyyən`,
        `fərdi`,
        `illustürasiya, şəkil, rəsm`,
        `otel`,
        `müsahibə`,
        `görünməz`,
        `qaydasız`,
        `maddə, çeşit
        `,
        `çaydan, qazan`,
        `açar`,
        `körpə, uşaq`,
        `quzu`,
        `dil`,
        `hüquq`,
        `boş vaxt`,
        `səviyyə`,
        `ədəbiyyat`,
        `zibil, tullantı
        `,
        `tək, tənha, yalqız`,
        `uzun`,
        `yük maşını`,
        `maşın`,
        `bəşəriyyət`,
        `əqli, psixi`,
        `xəbərçi, qasid, elçi`,
        `metod, üsul
        `,
        `hərbi`,
        `yazıq`,
        `an, dəqiqə`,
        `siçan, siçanlar`,
        `film`,
        `qonşu`,
        `xəbər`,
        `Şimal-Cənub-Qərb-Şərq`,
        `heç nə`,
        `roman`,
        `tibb bacısı`,
        `tez-tez
        `,
        `yağ, neft`,
        `dəbdən düşmüş`,
        `yalnız`,
        `imkan, məqam, əlverişli şərait`,
        `nikbin, optimist`,
        `oval, yumurta şəkilli`,
        `soba`,
        `səhifə`,
        `kağız; qəzet`,
        `xüsusi`,
        `şaftalı`,
        `karandaş`,
        `qələm dostu`,
        `qəpik, quruş`,
        `təqaüdçü`,
        `faiz`,
        `bəlkə, çox güman ki`,
        `daimi`,
        `insan`,
        `şəkil`,
        `önlük`,
        `təyyarə`,
        `qalın taxta, söykənəcək, dayaq`,
        `boşqab`,
        `gavalı`,
        `kök, gombul `,
        `cib`,
        `sıyıq`,
        `hambal, yükdaşıyan
        `,
        `müsbət`,
        `torba, çanta
        `,
        `əvvəlki`,
        `çox güman ki
        `,
        `gəlir`,
        `tərəqqi, inkişaf`,
        `lahiyə`,
        `doğru, düzgün, uyğun, münasib
        `,
        `atalar sözü`,
        `puding`,
        `it balası`,
        `məqsəd`,
        `cəld, sürətli`,
        `çiy`,
        `olduqca, xeyli, daha çox`,
        `səbəb`,
        `soyducu`,
        `qaçqın`,
        `əlaqə`,
        `nisbi, qohum`,
        `intibah`,
        `sakin`,
        `kurort`,
        `yerdə qalan`,
        `düyü`,
        `çəhrayı`,
        `qurban`,
        `satış`,
        `eyni`,
        `nümunə`,
        `şəkil, səhnə`,
        `məktəb`,
        `dəniz`,
        `oturacaq, yer`,
        `sensasiyalı`,
        `məntiqli, ağıllı`,
        `dayaz`,
        `iti, dəqiq, kəskin`,
        `skaf, skaflar`,
        `mağaza`,
        `qısa`,
        `utancaq`,
        `sadə, adi`,
        `bacı`,
        `qul`,
        `dəri`,
        `səma`,
        `qəlyanaltı`,
        `sabun`,
        `kimsə`,
        `oğul`,
        `eynək`,
        `görməli`,
        `ərköyün, korlanmış, nazlı`,
        `ştat, dövlət`,
        `ögey ata`,
        `hələ də, sakit`,
        `quruluş`,
        `şəhər kənarı`,
        `ani, qəfil`,
        `günəş`,
        `səth`,
        `su idman növü`,
        `soyad`,
        `şirin`,
        `tapşırıq`,
        `çaydan`,
        `yeniyetmə`,
        `çadır`,
        `dəhşətli`,
        `toxuculuq`,
        `nəzəriyyə`,
        `qalın`,
        `üçüncü`,
        `boğaz`,
        `baş barmaq`,
        `pələng`,
        `sıx, dar, möhkəm`,
        `bugün`,
        `pamidor`,
        `sabah`,
        `olduqca, həmçinin`,
        `tərəfində, istiqamətində`,
        `şəhər`,
        `faciəvi`,
        `tramvay`,
        `yerdəyişmə`,
        `tunel`,
        `ədalətsiz`,
        `bölmə, hərbi hissə`,
        `qeyri-adi`,
        `üst`,
        `tərəvəz`,
        `könüllü`,
        `boş`,
        `pul kisəsi
        `,
        `müharibə`,
        `mal anbarı
        `,
        `zəif, gücsüz`,
        `toy`,
        `əzələli`,
        `nəm, yaş `,
        `bütün`,
        `vəhşi`,
        `ağıllı, müdrik`,
        `möcüzəvi`,
        `yara; yaralanmaq, yaralamaq`,
        `zoopark`,

    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 