
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `abroad`,
        `absolute`,
        `access`,
        `according (to)`,
        `acid`,
        `advance`,
        `age`,
        `aggressor`,
        `air`,
        `amazing`,
        `amount`,
        `animal`,
        `approximate`,
        `area`,
        `arm`,
        `aspect`,
        `baby`,
        `bandage`,
        `bold`,
        `brave`,
        `bread`,
        `brilliant`,
        `business`,
        `busy`,
        `butcher`,
        `calm`,
        `camel`,
        `cancer`,
        `canteen`,
        `capable`,
        `capital`,
        `castle`,
        `cattle`,
        `ceremony`,
        `chance`,
        `channel`,
        `chapter`,
        `chicken`,
        `charity`,
        `child, children`,
        `clay`,
        `coin`,
        `cold`,
        `colour`,
        `comic`,
        `convenient`,
        `convention`,
        `cottage`,
        `culture`,
        `currency`,
        `daughter`,
        `deaf`,
        `death`,
        `debate`,
        `decker (double) bus `,
        `delicious`,
        `dentist`,
        `dessert`,
        `diary`,
        `dictionary`,
        `direction`,
        `disaster`,
        `donkey`,
        `drug = medicine`,
        `dull`,
        `each`,
        `elegant`,
        `elephant`,
        `enterprise`,
        `especially`,
        `event`,
        `evil`,
        `excellent`,
        `extraordinary`,
        `family`,
        `fault`,
        `farm`,
        `favourite`,
        `fear`,
        `fence`,
        `final`,
        `flame`,
        `flight`,
        `flower`,
        `foot, feet`,
        `fork`,
        `frank`,
        `free`,
        `frequency`,
        `furniture`,
        `game`,
        `gay`,
        `giant`,
        `gift`,
        `girl`,
        `glass`,
        `gloomy`,
        `grammar`,
        `grandson`,
        `grape`,
        `grasshopper`,
        `green`,
        `group`,
        `guilty of`,
        `half`,
        `high`,
        `hill`,
        `home`,
        `honest`,
        `horrible`,
        `horse`,
        `hospitable`,
        `hot`,
        `however`,
        `hunger`,
        `ice`,
        `identical`,
        `idle`,
        `income`,
        `incomplete`,
        `indoors`,
        `intelligent`,
        `intense`,
        `intensive`,
        `irrelevant to`,
        `jealous of`,
        `jeans`,
        `jog`,
        `journey`,
        `juice`,
        `junior`,
        `kind`,
        `king`,
        `kitchen`,
        `knife`,
        `lab = laboratory`,
        `lake`,
        `lantern`,
        `lazy`,
        `licence = license`,
        `loud`,
        `luggage`,
        `lunch`,
        `luxurious`,
        `magazine`,
        `man, men `,
        `many, much `,
        `margin`,
        `master`,
        `martyr`,
        `maybe`,
        `Mediterranean`,
        `Ministry of Foreign Trade`,
        `mist`,
        `more`,
        `mosque`,
        `mother`,
        `mountain`,
        `mulberry`,
        `mushroom`,
        `mystery`,
        `nature`,
        `negotiation`,
        `nervous`,
        `nest`,
        `nevertheless`,
        `new`,
        `next`,
        `nice`,
        `nightingale`,
        `nowadays`,
        `obligation`,
        `obvious`,
        `odd`,
        `orange`,
        `orchard`,
        `ordinary`,
        `outdoors`,
        `outstanding`,
        `pair`,
        `palace`,
        `partial`,
        `pain`,
        `partner`,
        `passionate`,
        `passive`,
        `patient`,
        `patriotic`,
        `peace`,
        `people`,
        `pepper`,
        `philosopher`,
        `pig`,
        `pin`,
        `pirate`,
        `plain`,
        `playwright`,
        `plough`,
        `plumber`,
        `primary`,
        `profession`,
        `property`,
        `pure`,
        `quality`,
        `range = distance`,
        `relief`,
        `remarkable`,
        `reptile`,
        `room`,
        `rose`,
        `rough`,
        `routine`,
        `row`,
        `safe`,
        `satellite`,
        `scarf`,
        `scissors`,
        `screen`,
        `section`,
        `seed`,
        `see-saw `,
        `sentence`,
        `severe`,
        `sheet`,
        `shoes`,
        `shore`,
        `shorts`,
        `shower`,
        `silk`,
        `single`,
        `situation`,
        `skill`,
        `skirt`,
        `small`,
        `soccer`,
        `sociable`,
        `sock`,
        `sofa`,
        `soft`,
        `solar system`,
        `soldier`,
        `soup`,
        `sour`,
        `special`,
        `spectator`,
        `splendid`,
        `spot`,
        `spy`,
        `stars`,
        `statement`,
        `stick`,
        `story`,
        `storm`,
        `stress`,
        `string`,
        `striped`,
        `success`,
        `synthetic`,
        `tail`,
        `tale`,
        `tall`,
        `team`,
        `the girl on duty`,
        `theatre`,
        `then`,
        `thing`,
        `thirsty`,
        `thistle`,
        `though = although = in spite of`,
        `thousand`,
        `tie`,
        `time`,
        `together`,
        `tolerant`,
        `tongue`,
        `top`,
        `T-shirt`,
        `tube`,
        `Tuesday`,
        `unable`,
        `uncommon`,
        `underground = subway`,
        `unhealthy`,
        `unjust`,
        `unknown`,
        `unwilling`,
        `wall`,
        `water`,
        `well-known`,
        `while`,
        `wholesale`,
        `willing`,
        `wind`,
        `wine`,
        `wonders`,
        `wood`,
        `worth`,
        `year`,
        `yesterday`,
        `yet`,
        

    ]

    let aze =[ 
      `xaricdə, gəmidə`,
      `tam, bütöv`,
      `keçid, qoşulma`,
      `uyğun, uyğun olaraq`,
      `turşu, turşuluq`,
      `irəli getmə, yüksəlmə`,
      `yaş, əsr`,
      `təcavüzkar`,
      `hava`,
      `heyrətamiz, füsünkar`,
      `məbləğ`,
      `heyvan`,
      `təxmini, təqribi`,
      `sahə, ərazi`,
      `qol; silah`,
      `baxış, fikir`,
      `uşaq`,
      `bint, sarğı
      `,
      `qalın, cəsur`,
      `cəsur, qoçaq`,
      `çörək`,
      `mükəmməl`,
      `biznes`,
      `məşğul`,
      `qəssab`,
      `sakit, həyəcansız`,
      `dəvə`,
      `yara, xərçəng xəstəliyi`,
      `bufet, yeməkxana`,
      `bacarıqlı`,
      `paytaxt`,
      `qala`,
      `mal-qara`,
      `mərasim`,
      `şans, imkan`,
      `kanal`,
      `fəsil, bölmə`,
      `cücə`,
      `xeyriyyəçilik`,
      `uşaq, uşaqlar`,
      `plastilin, gil
      `,
      `qəpik`,
      `soyuq`,
      `rəng`,
      `gülməli`,
      `rahat, uyğun`,
      `iclas, konvensiya`,
      `kottec, taxta ev
      `,
      `mədəniyyət`,
      `valyuta`,
      `qız`,
      `kar`,
      `ölüm`,
      `debat`,
      `ikimərtəbəli avtobus`,
      `dadlı, ləziz`,
      `diş həkimi`,
      `desert, meyvəli xörək`,
      `gündəlik`,
      `lüğət`,
      `istiqamət`,
      `fəlakət`,
      `eşşək`,
      `dərman`,
      `maraqsız, sıxıcı`,
      `hər, hər biri
      `,
      `gözəl, yaraşıqlı`,
      `fil`,
      `müəssisə`,
      `xüsusilə`,
      `hadisə`,
      `şər, çox zərərli, pis,`,
      `əla, mükəmməl`,
      `qeyri-adi `,
      `ailə`,
      `səhv, günah, qəza
      `,
      `ferma`,
      `sevimli, istəkli
      `,
      `qorxmaq`,
      `hasar`,
      `son`,
      `od, alov`,
      `uçuş`,
      `gül`,
      `ayaq, ayaqlar`,
      `çəngəl, yaba`,
      `səmimi, mehriban`,
      `azad, boş, havayı`,
      `tezlik`,
      `mebel`,
      `oyun`,
      `şad`,
      `nəhəng`,
      `hədiyyə`,
      `qız`,
      `şüşə, stəkan`,
      `kədərli, tutqun `,
      `qrammatika`,
      `oğlan nəvəsi
      `,
      `üzüm`,
      `cırcırama`,
      `yaşıl`,
      `qrup`,
      `günahkar`,
      `yarı, yarısı
      `,
      `hündür, uca`,
      `zirvə, təpə`,
      `ev`,
      `vicdanlı`,
      `dəhşətli`,
      `at`,
      `qonaqpərvər`,
      `isti`,
      `baxmayaraq, amma, ancaq
      `,
      `aclıq`,
      `buz`,
      `eyni, oxşar`,
      `tənbəl, avara`,
      `gəlir`,
      `natamam`,
      `içəridə`,
      `zəkalı, ağıllı`,
      `sıx, gərgin, qızğın
      `,
      `intensiv`,
      `əlaqəsiz`,
      `qısqanc`,
      `cins şalvar`,
      `asta qaçış`,
      `səfər, səyahət`,
      `şirə`,
      `kiçik yaşlı`,
      `növ; mehriban`,
      `kral`,
      `mətbəx`,
      `bıçaq`,
      `laboratoriya`,
      `göl`,
      `fənər`,
      `tənbəl`,
      `lisenziya, icazə, hüquq`,
      `uca, səs-küylü`,
      `yük`,
      `qəlyanaltı`,
      `lüks`,
      `jurnal`,
      `kişi, kişilər`,
      `çox, çoxlu`,
      `kənar, qıraq`,
      `usta`,
      `şəhid`,
      `bəlkə, olabilər`,
      `Aralıq dənizi`,
      `Xarici Ticarət Nazirliyi`,
      `duman`,
      `daha böyük, daha çox`,
      `məscid`,
      `ana`,
      `dağ`,
      `tut`,
      `göbələk`,
      `sirr`,
      `təbiət`,
      `danışıq`,
      `hirsli, əsəbi`,
      `yuva`,
      `hərçənd ki, yenə də`,
      `təzə, yeni`,
      `növbəti`,
      `yaxşı, gözəl`,
      `bülbül`,
      `bu günlərdə, indi`,
      `öhdəçilik`,
      `açıq-aşkar`,
      `təki olmayan, qəribə, qeyri-adi
      `,
      `portağal`,
      `meyvə bağı, bostan
      `,
      `sadə, adi`,
      `açıq-havada`,
      `məşhur, tanınmış`,
      `cüt`,
      `saray`,
      `qismən`,
      `ağrı`,
      `tərəf-müqabili`,
      `tutuklu, ehtiraslı`,
      `məchul, passiv
      `,
      `səbrli; xəstə
      `,
      `vətənpərvərlik, millətçi
      `,
      `sülh`,
      `insanlar`,
      `istiot`,
      `filosof`,
      `donuz budu, vetçina`,
      `sancaq`,
      `dəniz qulduru`,
      `düz, aydın, açıq, aşkar`,
      `yazıçı`,
      `əkmək, şumlamaq`,
      `santexnik`,
      `ibtidai`,
      `sənət, peşə`,
      `mülk, mülkiyyət`,
      `saf, təmiz, şəffaf`,
      `keyfiyyət`,
      `məsafə`,
      `relyef`,
      `görkəmli, diqqətəlayiq`,
      `sürünənlər`,
      `otaq, boş yer`,
      `qızılgül`,
      `nahamar, kələ-kötür, kobud`,
      `rejim`,
      `sıra, cərgə
      `,
      `təhlükəsiz`,
      `peyk`,
      `şərf`,
      `qayçı`,
      `ekran`,
      `bölmə, bir hissə
      `,
      `toxum`,
      `taxta yelləncək`,
      `cümlə; ittiham/mühakimə etmək`,
      `sərt, ciddi
      `,
      `vərəq, kağız; mələfə`,
      `ayaqqabı`,
      `sahil`,
      `qısa şalvar, şortik`,
      `leysan, güclü yağış
      `,
      `ipək`,
      `subay, tək; gediş bileti`,
      `vəziyyət`,
      `ustalıq, bacarıq
      `,
      `yubka`,
      `balaca, kiçik `,
      `futbol`,
      `ünsiyyətli, yola gedən
      `,
      `corab, ayyaqqabı içliyi`,
      `divan`,
      `yumşaq`,
      `günəş sistemi
      `,
      `əsgər`,
      `sup, şorba
      `,
      `turş, acı`,
      `özəl, xüsusi `,
      `tamaşaçı`,
      `təmtəraqlı, dəbdəbəli
      `,
      `ləkə`,
      `cəsus`,
      `ulduzlar`,
      `bildiriş, ifadə, təsdiq etmə
      `,
      `çubuq; yapışdırmaq`,
      `nağıl`,
      `tufan, qasırğa`,
      `vurğu, stres`,
      `ip`,
      `zolaqlı`,
      `uğur, naliyyət`,
      `sintetik`,
      `quyruq`,
      `hekayə, nağıl`,
      `hündür`,
      `komanda`,
      `növbətçi qız`,
      `teatr`,
      `sonra`,
      `əşya`,
      `susuz`,
      `qanqal`,
      `baxmayaraq`,
      `min`,
      `qalstuk; bağlamaq, düyünləmək`,
      `vaxt, dəfə`,
      `birlikdə`,
      `dözümlü`,
      `dil`,
      `üst, yuxarı`,
      `mayka`,
      `boru, kanal`,
      `çərşənbə axşamı`,
      `bacarıqsız`,
      `qeyri-adi`,
      `metro, yeraltıkeçid`,
      `sağlam olmayan, xəstə `,
      `ədalətsiz`,
      `naməlum, tanınmayan`,
      `istəksiz`,
      `divar`,
      `su; sulamaq`,
      `məşhur, tanınmış `,
      `müddətində, ərzində`,
      `topdansatış`,
      `istəkli, könüllü
      `,
      `külək`,
      `şərab, çaxır`,
      `həvəskarlar`,
      `ağac, meşə, taxta`,
      `dəyər`,
      `il`,
      `dünən`,
      `hələ, hələ də, indiyədək`,
    
    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 