
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `absent`,
        `accent`,
        `accountant`,
        `accurate`,
        `adult`,
        `afternoon`,
        `alone`,
        `angle`,
        `another`,
        `ant`,
        `antique`,
        `anxious`,
        `apartment`,
        `army`,
        `available`,
        `average`,
        `baggage`,
        `ball`,
        `basket`,
        `because`,
        `beech`,
        `bell`,
        `belt`,
        `bench`,
        `beside`,
        `bicycle = bike `,
        `bill`,
        `blue`,
        `body`,
        `bottle`,
        `bucket`,
        `bush`,
        `calendar`,
        `career`,
        `cathedral`,
        `centre`,
        `chalk`,
        `chemist`,
        `cinema`,
        `class`,
        `colonist`,
        `comer`,
        `committee`,
        `commodity`,
        `compartment`,
        `condition`,
        `conflict`,
        `cool`,
        `corner`,
        `corridor`,
        `crazy`,
        `crew = staff`,
        `crisp`,
        `crop`,
        `curtain`,
        `custom`,
        `customer`,
        `danger`,
        `dawn`,
        `dead`,
        `debt`,
        `deck`,
        `description`,
        `desk`,
        `detail`,
        `dirty`,
        `disease = illness`,
        `doll = toy`,
        `dormitory`,
        `dreadful`,
        `durable`,
        `during`,
        `eager for`,
        `else`,
        `enormous`,
        `entire`,
        `entry`,
        `envious`,
        `environment`,
        `equal`,
        `eraser`,
        `essay`,
        `everybody = everyone`,
        `everything`,
        `evidence`,
        `extremely`,
        `factory`,
        `faithful to`,
        `familiar`,
        `famous/outstanding`,
        `far`,
        `fare`,
        `fashionable`,
        `feather`,
        `feature`,
        `few`,
        `figure`,
        `flour`,
        `foreign`,
        `forest`,
        `fortune`,
        `four`,
        `fridge`,
        `frost`,
        `fun`,
        `further`,
        `garage`,
        `garden`,
        `general`,
        `generation`,
        `ghost`,
        `glad`,
        `gold`,
        `graceful`,
        `gradual`,
        `grateful`,
        `grey`,
        `grid`,
        `habit`,
        `hard`,
        `headache`,
        `heavy`,
        `heart`,
        `hospital`,
        `how`,
        `huge`,
        `idea`,
        `in this way`,
        `infection`,
        `institute`,
        `international`,
        `intolerable`,
        `irresponsible`,
        `island`,
        `jam`,
        `jail = prison`,
        `job`,
        `jug`,
        `lamp`,
        `large`,
        `late`,
        `layer`,
        `leaf, leaves`,
        `lesson`,
        `letter`,
        `lettuce`,
        `library`,
        `life`,
        `liver`,
        `loaf, loaves`,
        `loch = lake `,
        `logical`,
        `manuscript`,
        `measure`,
        `meat`,
        `member`,
        `mild`,
        `mint`,
        `miracle`,
        `mistake`,
        `mood`,
        `morning`,
        `motionless`,
        `mouth`,
        `muscle`,
        `must`,
        `native`,
        `near`,
        `neck`,
        `nephew`,
        `never`,
        `newspaper`,
        `niece`,
        `none`,
        `nourishing`,
        `nut`,
        `officer`,
        `olive`,
        `one another`,
        `opinion`,
        `opposite`,
        `other`,
        `otherwise`,
        `painstaking`,
        `parade`,
        `parents`,
        `parlour`,
        `parrot`,
        `party`,
        `passenger`,
        `pasta`,
        `peninsula`,
        `perfect`,
        `pessimistic`,
        `pillow`,
        `playground`,
        `photo`,
        `poor`,
        `population`,
        `power`,
        `pre-holiday`,
        `price`,
        `proud of`,
        `quiet`,
        `radiation`,
        `railway station`,
        `random`,
        `rat`,
        `ready`,
        `realist`,
        `reasonable`,
        `roll`,
        `religion`,
        `round`,
        `rude`,
        `sack`,
        `salad`,
        `salt`,
        `science`,
        `second`,
        `seldom`,
        `self-confident `,
        `self-contained `,
        `shade`,
        `shirt`,
        `short of money`,
        `silver`,
        `sir`,
        `slow`,
        `smart`,
        `sometimes`,
        `song`,
        `sort`,
        `species`,
        `speech`,
        `square`,
        `stairs`,
        `status`,
        `step-mother`,
        `sticky`,
        `stone`,
        `stout`,
        `strange`,
        `strict`,
        `sugar`,
        `sum`,
        `supper`,
        `surgeon`,
        `sword`,
        `tablet`,
        `tape`,
        `tears`,
        `telex`,
        `term`,
        `thin`,
        `thinker`,
        `through`,
        `tonight`,
        `tool`,
        `tooth, teeth`,
        `totally`,
        `tough`,
        `tower`,
        `township`,
        `traffic`,
        `trash`,
        `tray`,
        `trouble`,
        `true`,
        `turkey`,
        `tutor`,
        `twin`,
        `typical`,
        `uncertain`,
        `unfashionable`,
        `unique`,
        `unsuccessful`,
        `unwise`,
        `upset`,
        `upstairs`,
        `urgent`,
        `usual`,
        `usually`,
        `vacuum cleaner`,
        `village`,
        `violet`,
        `voice`,
        `waitress`,
        `wardrobe`,
        `warm`,
        `wave`,
        `weather`,
        `well-brought `,
        `well-dressed`,
        `well-educated `,
        `wheel`,
        `word`,
        `wrestler`,
        `zero`,
        `zone`,



    ]

    let aze =[ 
        `olmayan, iştirak etməyən`,
        `tələffüz tərzi`,
        `mühasib`,
        `dəqiq, səliqəli`,
        `böyüklər`,
        `günorta`,
        `tək, tənha, yalqız`,
        `bucaq`,
        `başqa`,
        `qarışqa`,
        `qədim`,
        `narahat`,
        `mənzil`,
        `ordu`,
        `mümkün, əlverişli`,
        `orta`,
        `baqaj, yük`,
        `top`,
        `səbət`,
        `çünki`,
        `fıstıq`,
        `zəng`,
        `kəmər`,
        `skamya`,
        `yanında`,
        `velosiped`,
        `hesab`,
        `mavi`,
        `bədən, cisim`,
        `butulka, şüşə`,
        `vedrə`,
        `kol`,
        `təqvim`,
        `karyera`,
        `baş kilsə`,
        `mərkəz`,
        `təbaşir`,
        `kimyaçı, aptekçi
        `,
        `kino`,
        `sinif`,
        `müstəmləkəçi`,
        `gəlmə, özgə`,
        `komitə`,
        `mal, əmtəə`,
        `kupe, şöbə`,
        `şərait, vəziyyət, şərt`,
        `münaqişə`,
        `sərin, soyuq-qanlı`,
        `künc`,
        `dəhliz`,
        `dəli, ağılsız, çılğın`,
        `ekipaj, heyət
        `,
        `xırda-xırda doğranmış qızartma kartof`,
        `məhsul`,
        `pərdə`,
        `adət-ənənə; alış-veriş`,
        `müştəri`,
        `təhlükə`,
        `sübh`,
        `ölü`,
        `borc (pul)`,
        `göyərtə`,
        `təsvir, xarakteristika`,
        `iş stolu, parta`,
        `detal, ətraflı məlumat`,
        `çirkli`,
        `xəstəlik`,
        `oyuncaq`,
        `yataqxana`,
        `qorxulu, dəhşətli, acıqlı, hirsli`,
        `dözümlü, dayanıqlı`,
        `müddətində, ərzində`,
        `istəkli, həvəsli (keen on)`,
        `daha, başqa`,
        `böyük, nəhəng`,
        `tam, bütöv`,
        `yazı, qeyd, giriş, qapı`,
        `paxıl, qısqanc`,
        `ətraf mühit`,
        `bərabər`,
        `pozan`,
        `inşa`,
        `hər kəs`,
        `hər şey`,
        `sübut`,
        `son dərəcə`,
        `zavod, fabrik`,
        `sadiq, vəfalı`,
        `tanış`,
        `məşhur, tanınmış`,
        `uzaq`,
        `bilet xərci, yol pulu`,
        `dəbdə olan `,
        `lələk`,
        `xüsusiyyət`,
        `az`,
        `bədən, rəqəm`,
        `un`,
        `xarici`,
        `meşə`,
        `bəxt, şans, tale`,
        `dörd`,
        `soyducu`,
        `buz, şaxta`,
        `əyləncə`,
        `sonrakı`,
        `qaraj`,
        `bağ, bağça`,
        `ümumi`,
        `nəsil`,
        `ruh`,
        `şad`,
        `qızıl`,
        `zərif, incə, gözəl`,
        `tədricən`,
        `minnətdar`,
        `boz`,
        `cədvəl`,
        `vərdiş`,
        `çətin, gərgin `,
        `baş ağrısı`,
        `ağır`,
        `ürək`,
        `xəstəxana`,
        `necə`,
        `nəhəng, böyük`,
        `ideya, fikir`,
        `bu yolla`,
        `infeksiya, yoluxma`,
        `institut`,
        `beynəlxalq`,
        `dözülməz`,
        `məsuliyyətsiz`,
        `ada`,
        `meyvə əzməsi; tıxac
        `,
        `həbsxana; həbs etmək`,
        `iş`,
        `küpə, bardaq, kuzə`,
        `lampa`,
        `geniş, böyük`,
        `gec`,
        `qat`,
        `yarpaq, yarpaqlar`,
        `dərs`,
        `məktub; hərf`,
        `salat, kahı`,
        `kitabxana`,
        `həyat`,
        `qaraciyər`,
        `bulka, bulkular`,
        `göl, körfəz`,
        `məntiqi`,
        `əlyazma`,
        `ölçü; ölçmək`,
        `ət`,
        `üzv`,
        `mülayim, yumşaq`,
        `nanə`,
        `möcüzə`,
        `səhv, yanlış`,
        `əhval-ruhiyyə`,
        `səhərlər`,
        `hərəkətsiz`,
        `ağız`,
        `əzələ; güc, qüvvə`,
        `malı, məli`,
        `doğma`,
        `yaxın`,
        `boyun`,
        `qardaşoğlu`,
        `heç vaxt`,
        `qəzet`,
        `qardaş qızı, bacı qızı
        `,
        `heç kim, heç nə`,
        `qidalı`,
        `fındıq`,
        `zabit`,
        `zeytun`,
        `bir-birini (3 və daha çox adam)
        `,
        `düşüncə, fikir`,
        `qarşı, üzbəüz, əks`,
        `digər, başqa`,
        `əks halda, yoxsa`,
        `zəhmətkeş, əməksevər`,
        `parad, təntənə, bayram`,
        `valideynlər`,
        `qonaq otağı`,
        `tutuquşu`,
        `şənlik, qonaqlıq`,
        `sərnişin`,
        `makaron, xəmir xörəkləri`,
        `yarımada`,
        `mükəmməl, əla, bitmiş
        `,
        `bədbin, pessimist`,
        `yastıq`,
        `oyun sahəsi
        `,
        `şəkil (kamera ilə`,
        `kasıb`,
        `əhali`,
        `güc`,
        `bayramqabağı`,
        `qiymət`,
        `qürurlu, məğrur`,
        `sakit, səssiz`,
        `radiyasiya`,
        `dəmiryol stansiyası`,
        `təsadüfi`,
        `siçan`,
        `hazır`,
        `realist`,
        `məqbul, əlverişli, sərfəli
        `,
        `rulet, rulon, bulku; fırlatmaq`,
        `din, inanc`,
        `dairəvi, yumru`,
        `kobud`,
        `kisə, çuval`,
        `salat`,
        `duz`,
        `elm`,
        `ikinci; saniyə`,
        `hərdən, nadir hallarda`,
        `özündən əmin, özünə güvənən`,
        `qaraqabaq`,
        `kölgə; kölgələnmək`,
        `köynək`,
        `pulu az olmaq`,
        `gümüş`,
        `cənab`,
        `yavaş`,
        `ağıllı, yaraşıqlı`,
        `hərdən, bəzən`,
        `mahnı`,
        `növ, çeşid`,
        `növ`,
        `nitq`,
        `kvadrat, meydan
        `,
        `pilləkanlar, nərdivan`,
        `status, vətəndaşlıq vəziyyəti`,
        `ögey ana`,
        `yapışqan`,
        `daş`,
        `kök, gombu`,
        `qəribə, yad `,
        `ciddi`,
        `şəkər tozu`,
        `miqdar, hesab; hesablamaq`,
        `şam yeməyi`,
        `cərrah`,
        `qılınc`,
        `həb`,
        `lent, maqnitafon`,
        `göz yaşı`,
        `qədim yazı maşını (əl ilə)`,
        `müddət, dövr, rüb, termin`,
        `arıq, nazik `,
        `düşünən adam, filosof`,
        `vasitəsilə, arasından, içərisəndən`,
        `bu axşam`,
        `alət`,
        `diş, dişlər`,
        `cəm olaraq`,
        `bərk, sərt, kobud`,
        `qala`,
        `bölgə`,
        `nəqliyyat`,
        `tullantı`,
        `sini (podnus)`,
        `narahatlıq`,
        `doğru, düzgün`,
        `hind toyuğu`,
        `tərbiyəçi, müəllim`,
        `əkiz`,
        `səciyyəvi`,
        `qeyri-müəyyən, şübhəli`,
        `dəbdən düşmüş`,
        `tək, vahid, yeganə, oxşarı olmayan`,
        `qeyri-müvəffəq`,
        `axmaq, səfeh
        `,
        `kədərli, qəmgin; kədərləndirmək, alt-üst etmək`,
        `üst mərtəbələr`,
        `təcili, təxirəsalınmaz, vacib, mühüm`,
        `adi, adəti üzrə`,
        `adətən`,
        `tozsoran`,
        `kənd`,
        `bənövşə`,
        `səs`,
        `yeməkpaylayan, ofisant`,
        `paltar skafı`,
        `isti, ilıq `,
        `dalğa; əl yelləmək, sağollaşmaq`,
        `hava`,
        `tərbiyəli`,
        `yaxşı geyinmiş`,
        `savadlı, təhsilli`,
        `çarx`,
        `söz`,
        `güləşçi`,
        `sıfır`,
        `zona, ərazi`,


     

    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 