
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `able`,
        `accident`,
        `administrative`,
        `again`,
        `agriculture`,
        `alike`,
        `already`,
        `alternative`,
        `always`,
        `ambition`,
        `among`,
        `ancient`,
        `anger`,
        `asleep`,
        `awful`,
        `bank`,
        `banner`,
        `basic`,
        `beauty`,
        `big`,
        `blouse`,
        `boat`,
        `boots`,
        `box`,
        `boy`,
        `branch`,
        `bridge`,
        `brown`,
        `cabbage`,
        `cage`,
        `cap`,
        `captain`,
        `cardinal`,
        `cartoon`,
        `cave`,
        `caviar`,
        `ceiling`,
        `certain`,
        `chair`,
        `church`,
        `circle`,
        `circus`,
        `city`,
        `clever`,
        `climate`,
        `cloth`,
        `coal`,
        `coat`,
        `comfortable`,
        `consonant`,
        `contract`,
        `cosy`,
        `could`,
        `country`,
        `courage`,
        `cousin`,
        `coward`,
        `crown`,
        `cup`,
        `day by day`,
        `dear`,
        `deer`,
        `diamond`,
        `dictation`,
        `diet`,
        `disabled`,
        `disadvantage`,
        `dishonourable`,
        `distant`,
        `door`,
        `dramatist`,
        `domestic`,
        `duty`,
        `ecological`,
        `effort`,
        `egg`,
        `either`,
        `energetic`,
        `engine`,
        `essential = crucial `,
        `even`,
        `evening`,
        `evidently`,
        `exact`,
        `exam`,
        `experience`,
        `false`,
        `fantastic`,
        `fascist`,
        `fellow`,
        `fine`,
        `flag = banner`,
        `flat`,
        `floor`,
        `flu`,
        `forever`,
        `fortress`,
        `forward`,
        `fresh`,
        `foyer`,
        `gallery`,
        `gate`,
        `genius`,
        `good`,
        `goose, geese `,
        `greedy`,
        `grief`,
        `8 gun = arm = weapon`,
        `guy`,
        `hair`,
        `hall`,
        `happy`,
        `harbor = port = dock`,
        `hard-working`,
        `hat`,
        `helicopter`,
        `hen`,
        `horror`,
        `history`,
        `honour`,
        `hostile to`,
        `human`,
        `humour`,
        `husband`,
        `ill`,
        `immigrant`,
        `impatient`,
        `important`,
        `incorrect`,
        `independent`,
        `indifferent to`,
        `industry`,
        `ingredient`,
        `injustice`,
        `insect`,
        `insurance`,
        `interior`,
        `internal`,
        `iron`,
        `issue`,
        `jewellery`,
        `kitten`,
        `lad`,
        `leather`,
        `left`,
        `legal`,
        `liberal`,
        `liquid`,
        `local`,
        `loudly = aloud `,
        `magic`,
        `magnificent`,
        `main`,
        `mainland`,
        `maths`,
        `major`,
        `meal`,
        `medieval`,
        `merry`,
        `mess`,
        `middle`,
        `midnight`,
        `mighty`,
        `milk`,
        `miserly`,
        `misery`,
        `modern`,
        `money`,
        `monument to smb.`,
        `mustard`,
        `narrow`,
        `nation`,
        `naught`,
        `neat = tidy`,
        `necessary`,
        `negative`,
        `neither`,
        `net`,
        `never mind`,
        `noble`,
        `nose`,
        `nursery school = kindergarten`,
        `oak tree `,
        `once`,
        `occasion`,
        `onion`,
        `outside`,
        `ox, oxen`,
        `ozone`,
        `parcel`,
        `path`,
        `period`,
        `petrol`,
        `phrase`,
        `planet`,
        `physics`,
        `pleasant`,
        `poem`,
        `poet`,
        `police`,
        `polite`,
        `portable`,
        `position`,
        `potato`,
        `prison`,
        `private = own `,
        `public`,
        `pupil`,
        `purple`,
        `queen`,
        `rare`,
        `really`,
        `receipt`,
        `reputation`,
        `regular`,
        `resource`,
        `right`,
        `river`,
        `road`,
        `role`,
        `sad`,
        `salary`,
        `secret`,
        `script`,
        `secure`,
        `selfish`,
        `sense`,
        `several`,
        `ship`,
        `should = ought to `,
        `shoulder`,
        `side`,
        `significant`,
        `silly`,
        `sitting-room`,
        `size`,
        `soda`,
        `soil`,
        `solidarity`,
        `soon`,
        `sorrow`,
        `specific`,
        `speed`,
        `sponge`,
        `stage`,
        `step`,
        `straight`,
        `strawberry`,
        `strong`,
        `stupid`,
        `summer`,
        `sweater`,
        `swine`,
        `syllable`,
        `symbol`,
        `tax`,
        `teacher`,
        `teddy bear`,
        `textbook`,
        `that's why`,
        `the same`,
        `theme`,
        `thief`,
        `thorn`,
        `thoughtful`,
        `thread`,
        `throughout`,
        `till, until `,
        `tiny`,
        `topic`,
        `towel`,
        `toy = doll`,
        `trip`,
        `tradition`,
        `trousers`,
        `twice`,
        `ugly`,
        `umbrella`,
        `unbelievable`,
        `unexpected`,
        `uniform`,
        `unity`,
        `unkind`,
        `vase`,
        `view`,
        `voyage`,
        `wealth`,
        `week`,
        `well`,
        `well-developed`,
        `wheat`,
        `wide`,
        `wife`,
        `winter`,
        `within`,
        `wolf`,
        `woman, women`,
        `workshop`,
        `world`,
        `yellow`,




       
    ]

    let aze =[
        `bacarıqlı` ,
        `hadisə`,
        `inzibati`,
        `yenidən`,
        `kənd təsərrüfatı`,
        `bənzər, oxşar`,
        `artıq`,
        `alternativ`,
        `həmişə`,
        `ambisiya, cəhd, arzu, iddia`,
        `arasında (3 və çox nəfər arasında)`,
        `qədim, köhnə, keçmiş`,
        `qəzəb`,
        `yuxulu`,
        `pis, dəhşətli `,
        `sahil; bank`,
        `bayraq`,
        `əsas`,
        `gözəllik`,
        `böyük`,
        `köynək`,
        `qayıq`,
        `çəkmə`,
        `qutu`,
        `oğlan`,
        `budaq, şöbə`,
        `körpü`,
        `qəhvəyi`,
        `kələm`,
        `qəfəs`,
        `papaq, şapka`,
        `kapitan`,
        `miqdar sayı`,
        `cizgi filmi
        `,
        `mağara`,
        `kürü`,
        `tavan`,
        `bəlli, müəyyən`,
        `stul, kafedra`,
        `kilsə`,
        `dairə`,
        `sirk`,
        `şəhər`,
        `ağıllı`,
        `iqlim, mühit`,
        `parça, süfrə`,
        `kömür`,
        `palto`,
        `rahat`,
        `samit`,
        `müqavilə, saziş, konkrat`,
        `rahat`,
        `bacarırdı`,
        `ölkə, kənd
        `,
        `cəsarət`,
        `xalaqızı, xalaoğlu`,
        `qorxaq`,
        `tac`,
        `fincan`,
        `günü-gündən`,
        `bahalı, əziz`,
        `maral, marallar`,
        `almaz`,
        `imla`,
        `pəhriz`,
        `əlil, şikəst`,
        `ziyan, zərər`,
        `şərəfsiz`,
        `uzaq`,
        `qapı`,
        `yazıçı, dram yazarı`,
        `evcil`,
        `vəzifə, gömrük vergisi`,
        `ekoloji`,
        `səy, cəhd`,
        `yumurta`,
        `ikisindən biri, həmçinin`,
        `enerjili, güclü, qüvvətli
        `,
        `mühərrik`,
        `əsas, vacib, çox önəmli`,
        `hətta`,
        `axşam`,
        `açıq-aydın, aşkar`,
        `dəqiq`,
        `imtahan`,
        `təcrübə`,
        `səhv, yanlış`,
        `qəribə, möcüzəli`,
        `faşist`,
        `gənc, yeniyetmə, kişi, oğlan`,
        `yaxşı, gözəl; cərimə`,
        `bayraq`,
        `ev`,
        `mərtəbə, döşəmə`,
        `zökəm`,
        `həmişəlik, əbədi`,
        `qala`,
        `qabaq, irəli`,
        `təzə`,
        `foye, guşə`,
        `qaleriya`,
        `darvaza`,
        `dahi, üstün zəkalı`,
        `yaxşı`,
        `qaz, qazlar`,
        `acgöz, xəsis`,
        `qəm, qüssə`,
        `silah`,
        `oğlan`,
        `saç tük`,
        `zal, salon`,
        `xoşbəxt, sevincli `,
        `liman`,
        `çalışqan`,
        `papaq`,
        `vertalyot`,
        `toyuq`,
        `dəhşət, qorxu`,
        `tarix`,
        `şərəf`,
        `düşmən`,
        `insan`,
        `yumor`,
        `ər`,
        `xəstə`,
        `miqrant`,
        `səbrsiz`,
        `vacib, mühüm `,
        `yanlış, səhv `,
        `müstəqillik`,
        `laqeyd`,
        `sənaye`,
        `tərkib hissəsi
        `,
        `ədalətsizlik`,
        `həşərat`,
        `sığorta`,
        `daxili, iç`,
        `daxili`,
        `dəmir; ütü, ütüləmək`,
        `məsələ, sual, buraxılış
        `,
        `daş-qaş
        `,
        `pişik balası`,
        `oğlan`,
        `dəri`,
        `sol`,
        `rəsmi, qanuni `,
        `azad fikirli
        `,
        `maye`,
        `yerli`,
        `ucadan`,
        `sehir`,
        `təmtəraqlı, möhtəşəm
        `,
        `vacib, əsas, başlıca`,
        `materik`,
        `riyaziyyat`,
        `əsas, başlıca, əksər`,
        `yemək`,
        `orta əsrlər`,
        `şən, sevincli `,
        `qarmaqarışıqlıq, dağınıqlıq`,
        `orta`,
        `gecəyarısı`,
        `güclü, qüdrətli`,
        `süd`,
        `xəsis`,
        `yoxsulluq, dilənçilik`,
        `müasir`,
        `pul`,
        `kiminsə abidəsi`,
        `xardal`,
        `dar, ensiz`,
        `xalq, millət`,
        `heç, sıfır`,
        `səliqəli`,
        `vacib, önəmli `,
        `inkar`,
        `heç biri`,
        `tor`,
        `eybi yoxdur, fikir vermə`,
        `alicənab`,
        `burun`,
        `uşaq bağçası`,
        `palıd ağacı`,
        `bir dəfə
        `,
        `tədbir, bəhanə`,
        `soğan`,
        `çöl, bayır`,
        `öküz, öküzlər`,
        `ozon`,
        `bağlama`,
        `cığır`,
        `dövr, zaman
        `,
        `neft, benzin`,
        `ifadə, cümlə`,
        `planet`,
        `fizika`,
        `xoş, gözəl`,
        `poema`,
        `şair`,
        `polislər`,
        `nəzakətli`,
        `daşınabilən`,
        `vəziyyət, yer, vəzifə`,
        `kartof`,
        `həbsxana`,
        `şəxsi, özəl `,
        `ictimai`,
        `şagird; göz bəbəyi`,
        `bənövşəyi rəng`,
        `kraliça`,
        `nadir, seyrək`,
        `həqiqətən, doğrudan`,
        `qəbz, resept`,
        `ad, şöhrət, şərəf`,
        `qaydalı`,
        `resurs, sərvətlər`,
        `sağ; hüquq; düz, doğru`,
        `çay`,
        `yol`,
        `rol`,
        `qəmgin, kədərli`,
        `maaş, əməkhaqqı`,
        `sirr`,
        `ssenari, əlifba, şrift`,
        `güvənli, təhlükəsiz`,
        `eqoist, özünüdüşünən`,
        `hiss, duyğu`,
        `bir neçə (+sayılan cəm)`,
        `gəmi`,
        `gərək, lazımlı`,
        `çiyin`,
        `tərəf`,
        `əhəmiyyətli, mühüm`,
        `axmaq, səfeh `,
        `qonaq otağı`,
        `ölçü`,
        `soda, mineral su`,
        `yer, torpaq`,
        `həmrəylik`,
        `tezliklə`,
        `qəm, qüssə`,
        `xüsusi`,
        `sürət`,
        `süngür`,
        `səhnə`,
        `addım, pillə`,
        `düz, düzgün
        `,
        `çiyələk`,
        `güclü`,
        `axmaq, kütbeyin`,
        `yay`,
        `sviter`,
        `donuz, donuzlar`,
        `heca`,
        `rəmz`,
        `vergi`,
        `müəllim`,
        `ayı balası`,
        `dərslik`,
        `ona görə də`,
        `eyni, həmin`,
        `mövzu`,
        `oğru`,
        `tikan`,
        `düşüncəli, fikirli`,
        `sap; saplamaq`,
        `hər yerdə, tamamilə`,
        `kimi, qədər`,
        `kiçik, bapbalaca`,
        `mövzu`,
        `dəsmal`,
        `oyuncaq`,
        `səyahət`,
        `adət-ənənə`,
        `şalvar`,
        `iki dəfə`,
        `çirkin`,
        `çətir`,
        `inanılmaz`,
        `gözlənilməz`,
        `uniforma`,
        `birlik, həmrəylik`,
        `qeyri-mehriban`,
        `güldan`,
        `görünüş, mənzərə
        `,
        `dəniz ilə səyahət`,
        `imkan, sərvət, var-dövlət
        `,
        `həftə`,
        `yaxşı`,
        `inkişaf etmiş
        `,
        `buğda`,
        `enli, geniş`,
        `arvad`,
        `qış`,
        `daxilində, içində`,
        `canavar`,
        `qadın, qadınlar`,
        `emalatxana`,
        `dünya`,
        `sarı`,


    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 