
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `abundance`,
        `accustom`,
        `adequate`,
        `bribery`,
        `bulwark`,
        `candidate`,
        `candle`,
        `carnation`,
        `cast`,
        `cautious`,
        `celebrated`,
        `cereal`,
        `charming`,
        `checker`,
        `cheek`,
        `chilly`,
        `chime`,
        `chimney`,
        `chop`,
        `chorus`,
        `circumstance`,
        `clerk`,
        `cloak`,
        `coco-nut`,
        `community`,
        `competent`,
        `comprehensive`,
        `compulsory`,
        `computation`,
        `congested`,
        `conscious of`,
        `constant`,
        `constellation`,
        `controversy`,
        `core`,
        `counter`,
        `counterfeit`,
        `couple`,
        `craft`,
        `cricket`,
        `cuisine`,
        `cult`,
        `curable`,
        `curio`,
        `curious`,
        `cushioning`,
        `daffodil`,
        `dagger`,
        `decimal fraction`,
        `deliberately`,
        `descendant`,
        `destruction`,
        `disillusioned`,
        `distinct`,
        `diversion`,
        `dizzy`,
        `downtown`,
        `draughts`,
        `drawer`,
        `eagle`,
        `ear`,
        `elbow`,
        `emergency`,
        `enlightenment`,
        `enthusiasm`,
        `equivalent`,
        `erection`,
        `eternal`,
        `exceptional`,
        `fable`,
        `fancy`,
        `fascinating`,
        `fatal`,
        `fate`,
        `felt tip `,
        `fig leaves`,
        `firm`,
        `fitter`,
        `fizzy drink `,
        `flake`,
        `for the sake of smb.`,
        `forecast`,
        `forefather`,
        `forehead`,
        `fragile`,
        `furious`,
        `gale`,
        `garland`,
        `generosity`,
        `gifted`,
        `glamorous`,
        `glossary`,
        `goal = target = aim `,
        `gorgeous`,
        `gossip`,
        `grave`,
        `grumpy`,
        `ham`,
        `hare = rabbit`,
        `harsh`,
        `hasty`,
        `heaven`,
        `herb`,
        `heritage`,
        `hilarious`,
        `hollow`,
        `holy`,
        `horn`,
        `hornbeam`,
        `humble`,
        `illegible`,
        `illiterate`,
        `immature`,
        `immense`,
        `impulse`,
        `impulsive`,
        `inadequate`,
        `incompetent`,
        `industrious`,
        `inevitable`,
        `infancy`,
        `infant`,
        `initial`,
        `inscription`,
        `integral`,
        `irresolute`,
        `jaw`,
        `junction`,
        `keen on `,
        `khanates`,
        `labour`,
        `lack`,
        `laundry`,
        `laureate`,
        `legislation`,
        `liar`,
        `linen`,
        `lip`,
        `lizard`,
        `loose`,
        `ludicrous`,
        `lung`,
        `mad`,
        `malnutrition`,
        `manner`,
        `marvellous`,
        `massacre`,
        `massive`,
        `mate`,
        `mature`,
        `melon field`,
        `merchant`,
        `mitten`,
        `muddy`,
        `mug`,
        `mute`,
        `mutton`,
        `mutual`,
        `nanny`,
        `nasty`,
        `notion`,
        `nutrition`,
        `on behalf of smb.`,
        `on condition that`,
        `on purpose`,
        `on the eve of`,
        `origin`,
        `orphan`,
        `owl`,
        `pal`,
        `pan`,
        `pavement`,
        `paw`,
        `perception`,
        `pursuit`,
        `phase`,
        `pigeon`,
        `pomegranate`,
        `pork`,
        `precious`,
        `prescription`,
        `presence`,
        `prey`,
        `prominent`,
        `prompt`,
        `proof`,
        `providing that`,
        `province`,
        `pullover`,
        `pumpkin`,
        `puppet`,
        `quadrangles`,
        `quarter`,
        `quest`,
        `quill`,
        `quiz`,
        `radish`,
        `rag`,
        `raisin`,
        `rate`,
        `raven`,
        `ray`,
        `redundant`,
        `refundable`,
        `reindeer`,
        `relevant to`,
        `resolute`,
        `ridiculous`,
        `ripe`,
        `ritual`,
        `rival`,
        `rooster`,
        `rubbish`,
        `rug`,
        `rural`,
        `saddle`,
        `saucepan`,
        `saucer`,
        `savant`,
        `scarce`,
        `schedule`,
        `sculptor`,
        `secular`,
        `shamrock`,
        `shepherd`,
        `sinister`,
        `skeleton`,
        `sleigh`,
        `slot`,
        `smooth`,
        `snowdrop`,
        `sore`,
        `spare time`,
        `spoon`,
        `squirrel`,
        `stableman`,
        `stationery`,
        `stepladder`,
        `stove`,
        `stubborn`,
        `sturgeon`,
        `substance`,
        `sufficient`,
        `superficial`,
        `suspicious`,
        `tap`,
        `tedious`,
        `temper`,
        `temple`,
        `tenant`,
        `tender`,
        `tense`,
        `terrace`,
        `thatch`,
        `therefore`,
        `tin`,
        `tip`,
        `tiresome`,
        `toast`,
        `toffees`,
        `torn`,
        `tortoise`,
        `torture`,
        `treasure`,
        `treaty`,
        `tribe`,
        `trick`,
        `troop`,
        `trunk`,
        `turbulent`,
        `turnip`,
        `tyranny`,
        `uneven`,
        `up-to-date`,
        `valley`,
        `veal`,
        `vehicle`,
        `victim`,
        `vigorous`,
        `violent`,
        `violin`,
        `vision`,
        `vital`,
        `whale`,
        `whatever`,
        `whisker`,
        `widow`,
        `wing`,
        `witch`,
        `witty`,
        `yacht`,
        `zealous`,
      
    ]


    let aze =[ 
        `bolluq, bərəkət, çoxluq
        `,
        `vərdiş`,
        `müvafiq, kafi`,
        `rüşvətxorluq, rüşvət`,
        `istehkam, qala divarı`,
        `namizəd`,
        `şam`,
        `qərənfil`,
        `aktyor heyəti`,
        `diqqətli, ehtiyatlı`,
        `məşhur, tanınmış`,
        `un məmulatı`,
        `cazibədar, cəlbedici`,
        `dama oyunu`,
        `yanaq`,
        `sərin, soyuq
        `,
        `zəng səsi
        `,
        `baca, tüstü borusu`,
        `kotlet`,
        `xor`,
        `vəziyyət, şərait`,
        `kargüzar, dəftərxana, məmur`,
        `plaş`,
        `kakos`,
        `cəmiyyət, icma, ortaqlıq`,
        `ixtisaslı, bacarıqlı, istedadlı`,
        `hərtərəfli, əhatəli, detallı`,
        `məcburi, icbari
        `,
        `hesablama, haqq-hesab
        `,
        `sıxılmış, tıxanmış`,
        `şüurlu`,
        `davamlı, sürəkli`,
        `bürc`,
        `mübahisə, münaqişə`,
        `əsas, özək`,
        `piştaxta, sayğac`,
        `saxta`,
        `cütlük`,
        `sənət, peşə, əl işi
        `,
        `ağacla oynanılan top oyun
        `,
        `mətbəx`,
        `sitayiş`,
        `müalicə oluna bilən`,
        `antiq əşya`,
        `hər şeylə çox maraqlanan`,
        `yumşaltmaq, yastıq düzəltmək`,
        `nərgizgülü`,
        `xəncər`,
        `onluq kəsr`,
        `qəsdən`,
        `övlad, nəvə-nəticə`,
        `dağıtma`,
        `məyus, ümidsiz`,
        `aydın, səlis `,
        `təxribat, yayındırma`,
        `gicəlləndirici, baş döndürücü
        `,
        `mərkəz`,
        `dama oyunu`,
        `çəkməcə (şkafın gözü)`,
        `qartal`,
        `qulaq`,
        `dirsək`,
        `təcili, çarəsiz hal`,
        `maarifçilik, aydınlatma`,
        `həvəs, ruh yüksəkliyi
        `,
        `ekvivalent`,
        `bina, abidə`,
        `əbədi, ölümsüz`,
        `xüsusi, qeyri-adi`,
        `təmsil`,
        `naxışlı, bəzəkli; xəyal (fantaziya) qurmaq
        `,
        `möhtəşəm, füsünkar, məftunedici
        `,
        `ölümcül`,
        `tale, bəxt, qismət`,
        `boya qələmi
        `,
        `əncir yarpağı
        `,
        `firma; möhkəm olmaq`,
        `çilingər, mexanik`,
        `qazlı içki`,
        `qar dənəciyi
        `,
        `kiminsə xatirinə`,
        `hava haqqında məlumat`,
        `ulu baba
        `,
        `insanın alnı`,
        `kövrək, tezsınan`,
        `qəzəbli, hirsli `,
        `fırtına, külək`,
        `çələng`,
        `səxavət, alicənablıq
        `,
        `qabiliyyətli, istedadlı`,
        `məftunedici`,
        `izahlı lüğət`,
        `məqsəd, hədəf`,
        `dəbdəbəli`,
        `qeybətçi, sözbaz; qeybət etmək`,
        `qəbir, məzar`,
        `deyingən`,
        `donuz budu, vetçina`,
        `dovşan`,
        `sərt`,
        `tələsik`,
        `səma, cənnət`,
        `ot, bitki`,
        `irs, miras`,
        `şən`,
        `içiboş, çuxur`,
        `müqəddəs`,
        `buynuz`,
        `vələs ağacı`,
        `təvəzükar`,
        `oxuna bilməyən, oxunmaz`,
        `oxuya-yaza bilməyən`,
        `yetişməmiş (insan)`,
        `möhtəşəm, hədsiz`,
        `istək, həvəs`,
        `qeyri-iradi, düşünmədən qərar verən`,
        `qeyri-kafi, yetərsiz`,
        `bacarıqsız, keyfiyyətsiz
        `,
        `çalışqan, zəhmətkeş`,
        `labüd, çarəsiz, qaçınılmaz`,
        `körpəlik, uşaqlıq`,
        `körpə, çağa
        `,
        `baş hərf, ilk hərf, ilkin`,
        `yazı, qısa ithaf`,
        `əsas, lazımi`,
        `qərarsız, iradəsiz`,
        `əng, çənə`,
        `yolayrıcı`,
        `maraqlı`,
        `xanlıqlar`,
        `əmək, zəhmət, iş
        `,
        `əksiklik`,
        `camaşırxana`,
        `laureat, mükafat`,
        `qanunvericilik`,
        `yalançı, gopçu`,
        `kətan`,
        `dodaq`,
        `kərtənkələ`,
        `boş, sərbəst`,
        `gülməli, gülünc`,
        `ağciyər`,
        `ağılsız, dəli`,
        `qidasızlıq, pis qidalanma`,
        `qayda, davranış, həyat tərzi
        `,
        `valehedici`,
        `qırğın, qətliam`,
        `iri, ağır`,
        `yoldaş, mat olmaq, cütləşmək`,
        `yetişkin (insan)
        `,
        `yemiş sahəsi
        `,
        `tacir`,
        `əlcək (təkbarmaqlı)`,
        `palçıqlı, çirkli`,
        `qədəh`,
        `lal, səssiz`,
        `qoyun əti`,
        `ortaq, qarşılıqlı`,
        `dayə`,
        `iyrənc`,
        `anlayış, fikir`,
        `qida`,
        `kiminsə adına`,
        `bir şərtlə`,
        `qəsdən`,
        `ərəfəsində`,
        `mənşə`,
        `yetim, kimsəsiz`,
        `bayquş`,
        `yoldaş`,
        `tava`,
        `səki, döşənmiş yol
        `,
        `pəncə; eşmək`,
        `qavrayış`,
        `təqib`,
        `mərhələ, faza`,
        `göyərçin`,
        `nar`,
        `donuz əti`,
        `dəyərli, qiymətli`,
        `resept, təyinat
        `,
        `iştirak`,
        `qənimət`,
        `görkəmli`,
        `çevik, cəld`,
        `fakt, dəlil; keçirməyən, buraxmayan`,
        `bir şərtlə`,
        `vilayət, əyalət`,
        `sviter, polver`,
        `boranı, balqabaq`,
        `oyuncaq adam`,
        `dördbucaqlı`,
        `rüb, 15 dəqiqə, dörddə bir`,
        `axtarış`,
        `lələk`,
        `sorğu`,
        `qırmızı turp`,
        `əsgi parçası`,
        `kişmiş`,
        `faiz, dərəcə, qiymət`,
        `qarğa`,
        `şüa`,
        `artık işə yaramayan, lazımsız, gərəksiz`,
        `pulu geri ödənilən`,
        `şimal maralı`,
        `uyğun, münasib, dəxli olan`,
        `cəsarətli, əzmli`,
        `gülməli`,
        `yetişmiş, dəymiş, yetkin`,
        `dini`,
        `rəqib`,
        `xoruz`,
        `zibil`,
        `kilim, xalça`,
        `ucqar, şəhərdən kənar`,
        `yəhər`,
        `qazan`,
        `nəlbəki`,
        `alim`,
        `nadir`,
        `cədvəl`,
        `heykəltəraş`,
        `dünyəvi`,
        `dovşan kələmi`,
        `çoban`,
        `yaramaz, çirkin, qəmli, kədərli`,
        `skelet`,
        `xizək`,
        `yarıq, kəsik`,
        `düz, hamar`,
        `novruzgülü`,
        `xəstə, yaralı`,
        `boş vaxt, asudə vaxt`,
        `qaşıq`,
        `dələ`,
        `mehtər, atabaxan`,
        `dəftərxana ləvazimatı`,
        `pilləkan, nərdivan`,
        `mətbəx piltəsi, soba
        `,
        `inadcıl, tərs`,
        `nərə balığı`,
        `maddə`,
        `kifayət qədər, kafi, yetərli`,
        `səthi, ötəri`,
        `şübhəli`,
        `su kranı`,
        `yorucu, darıxdırıcı`,
        `xasiyyət
        `,
        `məbəd`,
        `kirayəçi, icarəçi
        `,
        `zərif, incə, zəif`,
        `gərgin, qızğın
        `,
        `meydança, səki`,
        `saman`,
        `buna görə də, nəticədə`,
        `konserv bankası; qalay`,
        `faydalı məsləhət`,
        `yorucu, bezdirici`,
        `qızardılmış çörək`,
        `iris`,
        `cırıq, deşik`,
        `tısbağa`,
        `işgəncə, əzab`,
        `xəzinə`,
        `saziş, müqavilə`,
        `qəbilə, tayfa`,
        `hiylə, fırıldaq`,
        `izci qrupu, qoşun`,
        `gövdə, xortum`,
        `coşqun, həyəcanlı
        `,
        `ağ turp`,
        `zülm, qəddarlıq`,
        `nahamar`,
        `müasir`,
        `dərə`,
        `dana əti
        `,
        `minik vasitəsi`,
        `qurban, zərər çəkmiş`,
        `güclü, qüvvətli
        `,
        `zorakı, şiddətli`,
        `skripka`,
        `görünmə`,
        `canlı`,
        `balina`,
        `nə olur olsun, istənilən`,
        `bığ`,
        `dul`,
        `qanad`,
        `cadugər qadın`,
        `hazırcavab, zirək`,
        `yaxta, qayıq`,
        `qətiyyətli, iradəli, əzimli`,
  
         
    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 