
const a =[]
const b =[]
const result =[]



function randomIntFromInterval() { // min and max included 
    let word =[
        `abbey`,
        `affair`,
        `afterwards`,
        `aim`,
        `alarm-clock`,
        `alive`,
        `almond`,
        `also`,
        `altar`,
        `ambassador`,
        `amphibian`,
        `animated`,
        `antelope`,
        `appalling`,
        `apple`,
        `appropriate for`,
        `apricot`,
        `apron`,
        `architect`,
        `arrow`,
        `article`,
        `as`,
        `ashamed`,
        `at`,
        `attitude`,
        `audience`,
        `author`,
        `avenue`,
        `axe`,
        `bacon`,
        `balcony = verandah `,
        `bald`,
        `band`,
        `bauble`,
        `bay`,
        `bean`,
        `beast`,
        `bed`,
        `beef`,
        `beer`,
        `beloved`,
        `benefit`,
        `benevolent`,
        `beret`,
        `berry`,
        `bet`,
        `bilingual`,
        `bird`,
        `birthday`,
        `biscuit`,
        `bitter`,
        `biting winds`,
        `blank`,
        `blazer`,
        `blood`,
        `blow-dryer`,
        `blunt`,
        `bone`,
        `bonfire`,
        `booth`,
        `both`,
        `bowl`,
        `bracelet`,
        `bracket`,
        `breakfast`,
        `brick`,
        `bride`,
        `brother`,
        `brunch`,
        `brutal`,
        `buffalo`,
        `bullet`,
        `bunch`,
        `burst`,
        `bus`,
        `butterfly`,
        `cake`,
        `calf`,
        `cardboard`,
        `carrot`,
        `case`,
        `cell`,
        `century`,
        `cheese`,
        `cherry tree `,
        `click`,
        `cloud`,
        `coach`,
        `coast`,
        `code`,
        `column`,
        `compote`,
        `conductor`,
        `conference`,
        `co-operative`,
        `course`,
        `crime`,
        `cucumber`,
        `crowd`,
        `currently`,
        `cute`,
        `daily`,
        `dairy`,
        `damp`,
        `daybook`,
        `decision`,
        `deep ≠ shallow`,
        `degree`,
        `dense = thick`,
        `dish`,
        `dishonest`,
        `dissimilarity`,
        `dog`,
        `earth`,
        `easy`,
        `elder`,
        `enough`,
        `entrance`,
        `envelope`,
        `error`,
        `evergreen`,
        `excursion`,
        `expedition`,
        `experiment`,
        `expense`,
        `extract`,
        `fake`,
        `fame`,
        `fan`,
        `fat`,
        `fee`,
        `field`,
        `fond of`,
        `fox`,
        `friend = companion`,
        `frog`,
        `fruit`,
        `fundamental`,
        `glue`,
        `goat`,
        `grade`,
        `grapefruit`,
        `grass`,
        `great`,
        `ground`,
        `handicraft`,
        `handkerchief`,
        `harvest`,
        `height`,
        `here you are `,
        `hockey`,
        `honey`,
        `host`,
        `hour`,
        `humid`,
        `if`,
        `immediately`,
        `image`,
        `imprisonment`,
        `inattentive`,
        `incredible`,
        `ink`,
        `innocent of`,
        `instead of`,
        `interval`,
        `intervention`,
        `invalid`,
        `irreversible`,
        `jacket`,
        `jar`,
        `journal`,
        `just`,
        `knowledge`,
        `league`,
        `leg`,
        `legend`,
        `little`,
        `louse, lice`,
        `low`,
        `luck`,
        `matter`,
        `may (might) `,
        `meadow`,
        `medicine`,
        `minute`,
        `minor`,
        `mirror`,
        `modest`,
        `monster`,
        `month`,
        `motor`,
        `museum`,
        `night`,
        `nobody`,
        `noise`,
        `noon`,
        `normal`,
        `noun`,
        `numerous`,
        `ocean`,
        `of course`,
        `office`,
        `official`,
        `old`,
        `oral`,
        `ordinal`,
        `out of date `,
        `overseas`,
        `palm`,
        `part`,
        `participate`,
        `pattern`,
        `pear`,
        `pet`,
        `phonetics`,
        `poppy`,
        `popular`,
        `port`,
        `portrait`,
        `possible`,
        `potter`,
        `pound`,
        `powerful`,
        `pretty`,
        `principle`,
        `prize`,
        `purse = wallet`,
        `race`,
        `rapid`,
        `recently`,
        `reception`,
        `red`,
        `related to`,
        `republic`,
        `result`,
        `ribbon`,
        `rich`,
        `roof`,
        `royal`,
        `rusty`,
        `sacred`,
        `sand`,
        `seal`,
        `season`,
        `serious`,
        `sheep`,
        `sick`,
        `sight`,
        `silent`,
        `similar`,
        `simply`,
        `sincere`,
        `slightly`,
        `snake`,
        `solid`,
        `solution`,
        `source`,
        `spice`,
        `spring`,
        `stamp`,
        `station`,
        `stockings`,
        `street`,
        `subject`,
        `substantial`,
        `sure`,
        `swallow`,
        `table`,
        `talent`,
        `ticket`,
        `tidy = neat`,
        `timetable`,
        `title`,
        `tragedy`,
        `transport`,
        `truth`,
        `tulip`,
        `unbearable`,
        `uncle`,
        `uncountable`,
        `underneath`,
        `uninteresting`,
        `unofficial`,
        `unpleasant`,
        `untidy`,
        `usage`,
        `very`,
        `vessel=ship`,
        `victory`,
        `waterfall`,
        `way`,
        `window`,
        `without`,
        `witness`,
        `wrinkled`,
        `wool`,
        `wrong`,
        `yard`,
        `yogurt`,
        `young`,
        
    

    ]

    let aze =[ 
        `monastır, kilsə`,
        `məsələ, iş
        `,
        `sonra`,
        `məqsəd`,
        `zəngli saat`,
        `canlı, diri `,
        `badam`,
        `həmçinin`,
        `səcdəgah`,
        `səfir`,
        `suda quruda yaşayan`,
        `canlandırılmış`,
        `cüyür, antilop`,
        `qorxulu, dəhşətli
        `,
        `alma`,
        `uyğun, əlverişli`,
        `ərik, qaysı`,
        `önlük`,
        `memar`,
        `ox`,
        `məqalə`,
        `çünki`,
        `utancaq, utanmaq`,
        `da, də`,
        `münasibət`,
        `tamaşaçı`,
        `müəllif, yazıçı
        `,
        `xiyaban, yol`,
        `balta`,
        `donuz əti`,
        `balkon`,
        `keçəl`,
        `qrup, orkestr`,
        `muncuq, xırda oyuncaq
        `,
        `körfəz, buxta`,
        `lobya, dənə`,
        `heyvan, canavar`,
        `yataq, çarpayı`,
        `mal əti`,
        `pivə`,
        `sevimli`,
        `fayda, qazanc`,
        `xeyirxah, xoşdil`,
        `kepka`,
        `giləmeyvə`,
        `mərc, bəhs`,
        `ikidilli`,
        `quş`,
        `adgünü`,
        `peçenye`,
        `acı`,
        `şiddətli küləklər`,
        `boş, yazılmamış (kağız)`,
        `klub pencəyi`,
        `qan`,
        `fen, saç qurudan`,
        `küt`,
        `sümük`,
        `tonqal`,
        `köşk, dükan`,
        `hər ikisi`,
        `fincan, kasa`,
        `bilərzik`,
        `mötərizə`,
        `səhər yeməyi`,
        `kərpic`,
        `gəlin`,
        `qardaş`,
        `gecikmiş səhər yeməyi`,
        `zorakı, qəddar`,
        `camış`,
        `güllə`,
        `dəstə, salxım`,
        `partlayış`,
        `avtobus`,
        `kəpənək`,
        `tort, pirojna
        `,
        `buzov`,
        `karton`,
        `yerkökü`,
        `yeşik, kasa; hal; hadisə, problem`,
        `hücrə, xana`,
        `əsr, yüz il
        `,
        `pendir`,
        `gilas ağacı`,
        `basmaq, şıqqılatmaq
        `,
        `bulud`,
        `məşqçi; fayton; avtobus`,
        `sahil`,
        `kod, məcəllə
        `,
        `sütün`,
        `meyvə şirəsi`,
        `drijor, bilet yoxlayan`,
        `konferans, iclas
        `,
        `birgə, korperativ; əməkdaşlıq etmək`,
        `kurs; yeməyin əvvəli
        `,
        `cinayət`,
        `xiyar`,
        `kütlə, basırıq, basabas`,
        `hal-hazırda`,
        `sevimli, şirin, ağıllı`,
        `gündəlik`,
        `süd məhsulları
        `,
        `nəm, rütubətli`,
        `gündəlik`,
        `qərar`,
        `dərin ≠ dayaz
        `,
        `dərəcə`,
        `sıx, qalın
        `,
        `xörək; qab`,
        `vicdansız`,
        `fərq, müxtəliflik`,
        `it`,
        `yer kürəsi`,
        `asan`,
        `ailə üzvləri arasında yaşca böyük olmaq`,
        `kifayət qədər`,
        `giriş, giriş qapısı`,
        `zərf`,
        `səhv, yanlış`,
        `həmişəyaşıl
        `,
        `eksursiya`,
        `ekspedisiya, iş səyahəti
        `,
        `təcrübə`,
        `xərc`,
        `seçilmişş hissə, parça
        `,
        `saxta`,
        `şöhrət`,
        `azarkeş; serinkeş`,
        `kök, yağlı, gombul`,
        `təhsil haqqı`,
        `sahə, ərazi`,
        `sevən, istəyən, xoşlayan`,
        `tülkü`,
        `dost, yoldaş, şərik`,
        `qurbağa`,
        `meyvə`,
        `əsas, təməl
        `,
        `yapışqan`,
        `keçi`,
        `dərəcə, mərhələ`,
        `giləmeyvə`,
        `ot`,
        `böyük, görkəmli`,
        `yer, topraq`,
        `əl işi, peşə`,
        `əl dəsmalı, yaylıq`,
        `məhsul`,
        `hündürlük, boy`,
        `buyurun`,
        `xokkey`,
        `bal`,
        `ev sahibi`,
        `saat`,
        `nəm, rütubətli`,
        `əgər`,
        `dərhal`,
        `surət, təsvir`,
        `həbs, həbs edilmə`,
        `diqqətsiz`,
        `inanılmaz, ağlasığmaz `,
        `mürəkkəb (çernil)
        `,
        `günahsız`,
        `əvəzinə`,
        `fasilə`,
        `müdaxilə, vasitəçilik`,
        `etibarsız, əlil, şikəst`,
        `geri dönüşülməz
        `,
        `yaket`,
        `banka`,
        `jurnal`,
        `indicə; ədalətli`,
        `bilik`,
        `ittifaq, cəmiyyət`,
        `ayaq`,
        `əfsanə`,
        `balaca, kiçik, az`,
        `bit, bitlər`,
        `alçaq`,
        `uğur`,
        `maddə, cisim, məsələ, mövzu
        `,
        `imkanı olmaq, xahiş, icazə
        `,
        `çəmən`,
        `dərman`,
        `dəqiqə`,
        `kiçik, az`,
        `güzgü`,
        `təvəzükar`,
        `div`,
        `ay`,
        `mator, mühərrik`,
        `muzey`,
        `gecə`,
        `heç kim`,
        `səs-küy`,
        `günorta`,
        `normal`,
        `isim`,
        `çoxsaylı`,
        `okean`,
        `əlbəttə`,
        `ofis`,
        `rəsmi`,
        `köhnə, qoca, yaşlı`,
        `şifahi`,
        `sıra sayı`,
        `dəbdən düşmüş`,
        `dəniz üzərindən xarici ölkələr`,
        `palma ağacı`,
        `hissə, bölmə; bölmək, ayrılmaq`,
        `iştirak etmək`,
        `model, naxış, şablon`,
        `armud`,
        `ev heyvanı
        `,
        `fonetika`,
        `lalə`,
        `məşhur, populyar`,
        `port, liman`,
        `portret`,
        `mümkün`,
        `dulusçu`,
        `funt`,
        `güclü`,
        `gözəl, yaraşıqlı; olduqca`,
        `prinsip, müdür`,
        `mükafat`,
        `pul kisəsi`,
        `irq; yarış`,
        `cəld, çevik`,
        `son vaxtlar`,
        `qəbul, ziyafət`,
        `qırmızı`,
        `əlaqədar, qohum`,
        `respublika`,
        `nəticə`,
        `lent`,
        `varlı, zəngin`,
        `dam`,
        `kral, dəbdəbəli`,
        `paslı`,
        `müqəddəs`,
        `qum`,
        `suiti`,
        `fəsil`,
        `ciddi`,
        `qoyun, qoyunlar`,
        `xəstə`,
        `görünüş, baxış dairəsi
        `,
        `sakit, səssiz`,
        `oxşar`,
        `sadəcə olaraq`,
        `səmimi, təmizqəlbli`,
        `yüngül, az, biraz, birqədər`,
        `ilan`,
        `sərt, möhkəm, bərk`,
        `həll`,
        `mənbə`,
        `ədviyyat`,
        `yaz; bulaq`,
        `möhür`,
        `stansiya`,
        `corablar`,
        `küçə`,
        `mövzu, fənn`,
        `əhəmiyyətli, çox mühüm`,
        `əmin`,
        `qaranquş; udmaq
        `,
        `stol`,
        `istedad, məharət
        `,
        `bilet`,
        `təmiz, səliqəli`,
        `cədvəl`,
        `başlıq`,
        `faciə`,
        `nəqliyyat; daşımaq, nəql etmək`,
        `həqiqət`,
        `zanbaq, lalə
        `,
        `dözülməz`,
        `əmi`,
        `sayılabilməyən`,
        `aşağı hissə, altda`,
        `maraqsız`,
        `qeyri-rəsmi`,
        `xoş olmayan`,
        `natəmiz, çirkli, səliqəsiz`,
        `istifadə qaydası`,
        `çox`,
        `gəmi`,
        `qələbə`,
        `şəlalə`,
        `yol`,
        `pəncərə`,
        `sız, siz`,
        `şahid`,
        `qırışlı`,
        `yun`,
        `səhv, yanlış `,
        `həyət`,
        `qatıq`,
        `cavan, gənc`,
    

    ]
    let ozu = document.querySelector( ".ozu").value
    let second = document.querySelector(".second").value
   
    b[0]=second
    a[0]=ozu
   
    let randomu = Math.floor(Math.random()*((a[0]*1)-(b[0]*1))+(b[0])*1)
    document.querySelector(".English").innerHTML = word[randomu]
    document.querySelector(".Aze").innerHTML = aze[randomu]
    document.querySelector(".Aze").style.opacity = "0"
    console.log(aze.length,word.length)
    

  }


    function goster(){
        document.querySelector(".Aze").style.opacity = "1"
    }


  randomIntFromInterval()








  


 